<?php

use App\Models\Country;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
      $countries = [
          ['code' => 'AFG','name' => 'Afghanistan','region' => 'Asia','currency_code' => 'AFN','currency_name' => 'Afghan afghani','calling_code' => '93'],
          ['code' => 'ALA','name' => 'Åland Islands','region' => 'Europe','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '358'],
          ['code' => 'ALB','name' => 'Albania','region' => 'Europe','currency_code' => 'ALL','currency_name' => 'Albanian lek','calling_code' => '355'],
          ['code' => 'DZA','name' => 'Algeria','region' => 'Africa','currency_code' => 'DZD','currency_name' => 'Algerian dinar','calling_code' => '213'],
          ['code' => 'ASM','name' => 'American Samoa','region' => 'Oceania','currency_code' => 'USD','currency_name' => 'United State Dollar','calling_code' => '1684'],
          ['code' => 'AND','name' => 'Andorra','region' => 'Europe','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '376'],
          ['code' => 'AGO','name' => 'Angola','region' => 'Africa','currency_code' => 'AOA','currency_name' => 'Angolan kwanza','calling_code' => '244'],
          ['code' => 'AIA','name' => 'Anguilla','region' => 'Americas','currency_code' => 'XCD','currency_name' => 'East Caribbean dollar','calling_code' => '1264'],
          ['code' => 'ATA','name' => 'Antarctica','region' => 'Polar','currency_code' => 'AUD','currency_name' => 'Australian dollar','calling_code' => '672'],
          ['code' => 'ATG','name' => 'Antigua and Barbuda','region' => 'Americas','currency_code' => 'XCD','currency_name' => 'East Caribbean dollar','calling_code' => '1268'],
          ['code' => 'ARG','name' => 'Argentina','region' => 'Americas','currency_code' => 'ARS','currency_name' => 'Argentine peso','calling_code' => '54'],
          ['code' => 'ARM','name' => 'Armenia','region' => 'Asia','currency_code' => 'AMD','currency_name' => 'Armenian dram','calling_code' => '374'],
          ['code' => 'ABW','name' => 'Aruba','region' => 'Americas','currency_code' => 'AWG','currency_name' => 'Aruban florin','calling_code' => '297'],
          ['code' => 'AUS','name' => 'Australia','region' => 'Oceania','currency_code' => 'AUD','currency_name' => 'Australian dollar','calling_code' => '61'],
          ['code' => 'AUT','name' => 'Austria','region' => 'Europe','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '43'],
          ['code' => 'AZE','name' => 'Azerbaijan','region' => 'Asia','currency_code' => 'AZN','currency_name' => 'Azerbaijani manat','calling_code' => '994'],
          ['code' => 'BHS','name' => 'Bahamas','region' => 'Americas','currency_code' => 'BSD','currency_name' => 'Bahamian dollar','calling_code' => '1242'],
          ['code' => 'BHR','name' => 'Bahrain','region' => 'Asia','currency_code' => 'BHD','currency_name' => 'Bahraini dinar','calling_code' => '973'],
          ['code' => 'BGD','name' => 'Bangladesh','region' => 'Asia','currency_code' => 'BDT','currency_name' => 'Bangladeshi taka','calling_code' => '880'],
          ['code' => 'BRB','name' => 'Barbados','region' => 'Americas','currency_code' => 'BBD','currency_name' => 'Barbadian dollar','calling_code' => '1246'],
          ['code' => 'BLR','name' => 'Belarus','region' => 'Europe','currency_code' => 'BYN','currency_name' => 'New Belarusian ruble','calling_code' => '375'],
          ['code' => 'BEL','name' => 'Belgium','region' => 'Europe','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '32'],
          ['code' => 'BLZ','name' => 'Belize','region' => 'Americas','currency_code' => 'BZD','currency_name' => 'Belize dollar','calling_code' => '501'],
          ['code' => 'BEN','name' => 'Benin','region' => 'Africa','currency_code' => 'XOF','currency_name' => 'West African CFA franc','calling_code' => '229'],
          ['code' => 'BMU','name' => 'Bermuda','region' => 'Americas','currency_code' => 'BMD','currency_name' => 'Bermudian dollar','calling_code' => '1441'],
          ['code' => 'BTN','name' => 'Bhutan','region' => 'Asia','currency_code' => 'BTN','currency_name' => 'Bhutanese ngultrum','calling_code' => '975'],
          ['code' => 'BOL','name' => 'Bolivia (Plurinational State of)','region' => 'Americas','currency_code' => 'BOB','currency_name' => 'Bolivian boliviano','calling_code' => '591'],
          ['code' => 'BES','name' => 'Bonaire, Sint Eustatius and Saba','region' => 'Americas','currency_code' => 'USD','currency_name' => 'United States dollar','calling_code' => '5997'],
          ['code' => 'BIH','name' => 'Bosnia and Herzegovina','region' => 'Europe','currency_code' => 'BAM','currency_name' => 'Bosnia and Herzegovina convertible mark','calling_code' => '387'],
          ['code' => 'BWA','name' => 'Botswana','region' => 'Africa','currency_code' => 'BWP','currency_name' => 'Botswana pula','calling_code' => '267'],
          ['code' => 'BVT','name' => 'Bouvet Island','region' => '','currency_code' => 'NOK','currency_name' => 'Norwegian krone','calling_code' => ''],
          ['code' => 'BRA','name' => 'Brazil','region' => 'Americas','currency_code' => 'BRL','currency_name' => 'Brazilian real','calling_code' => '55'],
          ['code' => 'IOT','name' => 'British Indian Ocean Territory','region' => 'Africa','currency_code' => 'USD','currency_name' => 'United States dollar','calling_code' => '246'],
          ['code' => 'UMI','name' => 'United States Minor Outlying Islands','region' => 'Americas','currency_code' => 'USD','currency_name' => 'United States Dollar','calling_code' => ''],
          ['code' => 'VGB','name' => 'Virgin Islands (British)','region' => 'Americas','currency_code' => NULL,'currency_name' => '[D]','calling_code' => '1284'],
          ['code' => 'VIR','name' => 'Virgin Islands (U.S.)','region' => 'Americas','currency_code' => 'USD','currency_name' => 'United States dollar','calling_code' => '1 340'],
          ['code' => 'BRN','name' => 'Brunei Darussalam','region' => 'Asia','currency_code' => 'BND','currency_name' => 'Brunei dollar','calling_code' => '673'],
          ['code' => 'BGR','name' => 'Bulgaria','region' => 'Europe','currency_code' => 'BGN','currency_name' => 'Bulgarian lev','calling_code' => '359'],
          ['code' => 'BFA','name' => 'Burkina Faso','region' => 'Africa','currency_code' => 'XOF','currency_name' => 'West African CFA franc','calling_code' => '226'],
          ['code' => 'BDI','name' => 'Burundi','region' => 'Africa','currency_code' => 'BIF','currency_name' => 'Burundian franc','calling_code' => '257'],
          ['code' => 'KHM','name' => 'Cambodia','region' => 'Asia','currency_code' => 'KHR','currency_name' => 'Cambodian riel','calling_code' => '855'],
          ['code' => 'CMR','name' => 'Cameroon','region' => 'Africa','currency_code' => 'XAF','currency_name' => 'Central African CFA franc','calling_code' => '237'],
          ['code' => 'CAN','name' => 'Canada','region' => 'Americas','currency_code' => 'CAD','currency_name' => 'Canadian dollar','calling_code' => '1'],
          ['code' => 'CPV','name' => 'Cabo Verde','region' => 'Africa','currency_code' => 'CVE','currency_name' => 'Cape Verdean escudo','calling_code' => '238'],
          ['code' => 'CYM','name' => 'Cayman Islands','region' => 'Americas','currency_code' => 'KYD','currency_name' => 'Cayman Islands dollar','calling_code' => '1345'],
          ['code' => 'CAF','name' => 'Central African Republic','region' => 'Africa','currency_code' => 'XAF','currency_name' => 'Central African CFA franc','calling_code' => '236'],
          ['code' => 'TCD','name' => 'Chad','region' => 'Africa','currency_code' => 'XAF','currency_name' => 'Central African CFA franc','calling_code' => '235'],
          ['code' => 'CHL','name' => 'Chile','region' => 'Americas','currency_code' => 'CLP','currency_name' => 'Chilean peso','calling_code' => '56'],
          ['code' => 'CHN','name' => 'China','region' => 'Asia','currency_code' => 'CNY','currency_name' => 'Chinese yuan','calling_code' => '86'],
          ['code' => 'CXR','name' => 'Christmas Island','region' => 'Oceania','currency_code' => 'AUD','currency_name' => 'Australian dollar','calling_code' => '61'],
          ['code' => 'CCK','name' => 'Cocos (Keeling) Islands','region' => 'Oceania','currency_code' => 'AUD','currency_name' => 'Australian dollar','calling_code' => '61'],
          ['code' => 'COL','name' => 'Colombia','region' => 'Americas','currency_code' => 'COP','currency_name' => 'Colombian peso','calling_code' => '57'],
          ['code' => 'COM','name' => 'Comoros','region' => 'Africa','currency_code' => 'KMF','currency_name' => 'Comorian franc','calling_code' => '269'],
          ['code' => 'COG','name' => 'Congo','region' => 'Africa','currency_code' => 'XAF','currency_name' => 'Central African CFA franc','calling_code' => '242'],
          ['code' => 'COD','name' => 'Congo (Democratic Republic of the)','region' => 'Africa','currency_code' => 'CDF','currency_name' => 'Congolese franc','calling_code' => '243'],
          ['code' => 'COK','name' => 'Cook Islands','region' => 'Oceania','currency_code' => 'NZD','currency_name' => 'New Zealand dollar','calling_code' => '682'],
          ['code' => 'CRI','name' => 'Costa Rica','region' => 'Americas','currency_code' => 'CRC','currency_name' => 'Costa Rican colón','calling_code' => '506'],
          ['code' => 'HRV','name' => 'Croatia','region' => 'Europe','currency_code' => 'HRK','currency_name' => 'Croatian kuna','calling_code' => '385'],
          ['code' => 'CUB','name' => 'Cuba','region' => 'Americas','currency_code' => 'CUC','currency_name' => 'Cuban convertible peso','calling_code' => '53'],
          ['code' => 'CUW','name' => 'Curaçao','region' => 'Americas','currency_code' => 'ANG','currency_name' => 'Netherlands Antillean guilder','calling_code' => '599'],
          ['code' => 'CYP','name' => 'Cyprus','region' => 'Europe','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '357'],
          ['code' => 'CZE','name' => 'Czech Republic','region' => 'Europe','currency_code' => 'CZK','currency_name' => 'Czech koruna','calling_code' => '420'],
          ['code' => 'DNK','name' => 'Denmark','region' => 'Europe','currency_code' => 'DKK','currency_name' => 'Danish krone','calling_code' => '45'],
          ['code' => 'DJI','name' => 'Djibouti','region' => 'Africa','currency_code' => 'DJF','currency_name' => 'Djiboutian franc','calling_code' => '253'],
          ['code' => 'DMA','name' => 'Dominica','region' => 'Americas','currency_code' => 'XCD','currency_name' => 'East Caribbean dollar','calling_code' => '1767'],
          ['code' => 'DOM','name' => 'Dominican Republic','region' => 'Americas','currency_code' => 'DOP','currency_name' => 'Dominican peso','calling_code' => '1809'],
          ['code' => 'ECU','name' => 'Ecuador','region' => 'Americas','currency_code' => 'USD','currency_name' => 'United States dollar','calling_code' => '593'],
          ['code' => 'EGY','name' => 'Egypt','region' => 'Africa','currency_code' => 'EGP','currency_name' => 'Egyptian pound','calling_code' => '20'],
          ['code' => 'SLV','name' => 'El Salvador','region' => 'Americas','currency_code' => 'USD','currency_name' => 'United States dollar','calling_code' => '503'],
          ['code' => 'GNQ','name' => 'Equatorial Guinea','region' => 'Africa','currency_code' => 'XAF','currency_name' => 'Central African CFA franc','calling_code' => '240'],
          ['code' => 'ERI','name' => 'Eritrea','region' => 'Africa','currency_code' => 'ERN','currency_name' => 'Eritrean nakfa','calling_code' => '291'],
          ['code' => 'EST','name' => 'Estonia','region' => 'Europe','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '372'],
          ['code' => 'ETH','name' => 'Ethiopia','region' => 'Africa','currency_code' => 'ETB','currency_name' => 'Ethiopian birr','calling_code' => '251'],
          ['code' => 'FLK','name' => 'Falkland Islands (Malvinas)','region' => 'Americas','currency_code' => 'FKP','currency_name' => 'Falkland Islands pound','calling_code' => '500'],
          ['code' => 'FRO','name' => 'Faroe Islands','region' => 'Europe','currency_code' => 'DKK','currency_name' => 'Danish krone','calling_code' => '298'],
          ['code' => 'FJI','name' => 'Fiji','region' => 'Oceania','currency_code' => 'FJD','currency_name' => 'Fijian dollar','calling_code' => '679'],
          ['code' => 'FIN','name' => 'Finland','region' => 'Europe','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '358'],
          ['code' => 'FRA','name' => 'France','region' => 'Europe','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '33'],
          ['code' => 'GUF','name' => 'French Guiana','region' => 'Americas','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '594'],
          ['code' => 'PYF','name' => 'French Polynesia','region' => 'Oceania','currency_code' => 'XPF','currency_name' => 'CFP franc','calling_code' => '689'],
          ['code' => 'ATF','name' => 'French Southern Territories','region' => 'Africa','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => ''],
          ['code' => 'GAB','name' => 'Gabon','region' => 'Africa','currency_code' => 'XAF','currency_name' => 'Central African CFA franc','calling_code' => '241'],
          ['code' => 'GMB','name' => 'Gambia','region' => 'Africa','currency_code' => 'GMD','currency_name' => 'Gambian dalasi','calling_code' => '220'],
          ['code' => 'GEO','name' => 'Georgia','region' => 'Asia','currency_code' => 'GEL','currency_name' => 'Georgian Lari','calling_code' => '995'],
          ['code' => 'DEU','name' => 'Germany','region' => 'Europe','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '49'],
          ['code' => 'GHA','name' => 'Ghana','region' => 'Africa','currency_code' => 'GHS','currency_name' => 'Ghanaian cedi','calling_code' => '233'],
          ['code' => 'GIB','name' => 'Gibraltar','region' => 'Europe','currency_code' => 'GIP','currency_name' => 'Gibraltar pound','calling_code' => '350'],
          ['code' => 'GRC','name' => 'Greece','region' => 'Europe','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '30'],
          ['code' => 'GRL','name' => 'Greenland','region' => 'Americas','currency_code' => 'DKK','currency_name' => 'Danish krone','calling_code' => '299'],
          ['code' => 'GRD','name' => 'Grenada','region' => 'Americas','currency_code' => 'XCD','currency_name' => 'East Caribbean dollar','calling_code' => '1473'],
          ['code' => 'GLP','name' => 'Guadeloupe','region' => 'Americas','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '590'],
          ['code' => 'GUM','name' => 'Guam','region' => 'Oceania','currency_code' => 'USD','currency_name' => 'United States dollar','calling_code' => '1671'],
          ['code' => 'GTM','name' => 'Guatemala','region' => 'Americas','currency_code' => 'GTQ','currency_name' => 'Guatemalan quetzal','calling_code' => '502'],
          ['code' => 'GGY','name' => 'Guernsey','region' => 'Europe','currency_code' => 'GBP','currency_name' => 'British pound','calling_code' => '44'],
          ['code' => 'GIN','name' => 'Guinea','region' => 'Africa','currency_code' => 'GNF','currency_name' => 'Guinean franc','calling_code' => '224'],
          ['code' => 'GNB','name' => 'Guinea-Bissau','region' => 'Africa','currency_code' => 'XOF','currency_name' => 'West African CFA franc','calling_code' => '245'],
          ['code' => 'GUY','name' => 'Guyana','region' => 'Americas','currency_code' => 'GYD','currency_name' => 'Guyanese dollar','calling_code' => '592'],
          ['code' => 'HTI','name' => 'Haiti','region' => 'Americas','currency_code' => 'HTG','currency_name' => 'Haitian gourde','calling_code' => '509'],
          ['code' => 'HMD','name' => 'Heard Island and McDonald Islands','region' => '','currency_code' => 'AUD','currency_name' => 'Australian dollar','calling_code' => ''],
          ['code' => 'VAT','name' => 'Holy See','region' => 'Europe','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '379'],
          ['code' => 'HND','name' => 'Honduras','region' => 'Americas','currency_code' => 'HNL','currency_name' => 'Honduran lempira','calling_code' => '504'],
          ['code' => 'HKG','name' => 'Hong Kong','region' => 'Asia','currency_code' => 'HKD','currency_name' => 'Hong Kong dollar','calling_code' => '852'],
          ['code' => 'HUN','name' => 'Hungary','region' => 'Europe','currency_code' => 'HUF','currency_name' => 'Hungarian forint','calling_code' => '36'],
          ['code' => 'ISL','name' => 'Iceland','region' => 'Europe','currency_code' => 'ISK','currency_name' => 'Icelandic króna','calling_code' => '354'],
          ['code' => 'IND','name' => 'India','region' => 'Asia','currency_code' => 'INR','currency_name' => 'Indian rupee','calling_code' => '91'],
          ['code' => 'IDN','name' => 'Indonesia','region' => 'Asia','currency_code' => 'IDR','currency_name' => 'Indonesian rupiah','calling_code' => '62'],
          ['code' => 'CIV','name' => 'Côte d\'Ivoire','region' => 'Africa','currency_code' => 'XOF','currency_name' => 'West African CFA franc','calling_code' => '225'],
          ['code' => 'IRN','name' => 'Iran (Islamic Republic of)','region' => 'Asia','currency_code' => 'IRR','currency_name' => 'Iranian rial','calling_code' => '98'],
          ['code' => 'IRQ','name' => 'Iraq','region' => 'Asia','currency_code' => 'IQD','currency_name' => 'Iraqi dinar','calling_code' => '964'],
          ['code' => 'IRL','name' => 'Ireland','region' => 'Europe','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '353'],
          ['code' => 'IMN','name' => 'Isle of Man','region' => 'Europe','currency_code' => 'GBP','currency_name' => 'British pound','calling_code' => '44'],
          ['code' => 'ISR','name' => 'Israel','region' => 'Asia','currency_code' => 'ILS','currency_name' => 'Israeli new shekel','calling_code' => '972'],
          ['code' => 'ITA','name' => 'Italy','region' => 'Europe','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '39'],
          ['code' => 'JAM','name' => 'Jamaica','region' => 'Americas','currency_code' => 'JMD','currency_name' => 'Jamaican dollar','calling_code' => '1876'],
          ['code' => 'JPN','name' => 'Japan','region' => 'Asia','currency_code' => 'JPY','currency_name' => 'Japanese yen','calling_code' => '81'],
          ['code' => 'JEY','name' => 'Jersey','region' => 'Europe','currency_code' => 'GBP','currency_name' => 'British pound','calling_code' => '44'],
          ['code' => 'JOR','name' => 'Jordan','region' => 'Asia','currency_code' => 'JOD','currency_name' => 'Jordanian dinar','calling_code' => '962'],
          ['code' => 'KAZ','name' => 'Kazakhstan','region' => 'Asia','currency_code' => 'KZT','currency_name' => 'Kazakhstani tenge','calling_code' => '76'],
          ['code' => 'KEN','name' => 'Kenya','region' => 'Africa','currency_code' => 'KES','currency_name' => 'Kenyan shilling','calling_code' => '254'],
          ['code' => 'KIR','name' => 'Kiribati','region' => 'Oceania','currency_code' => 'AUD','currency_name' => 'Australian dollar','calling_code' => '686'],
          ['code' => 'KWT','name' => 'Kuwait','region' => 'Asia','currency_code' => 'KWD','currency_name' => 'Kuwaiti dinar','calling_code' => '965'],
          ['code' => 'KGZ','name' => 'Kyrgyzstan','region' => 'Asia','currency_code' => 'KGS','currency_name' => 'Kyrgyzstani som','calling_code' => '996'],
          ['code' => 'LAO','name' => 'Lao People\'s Democratic Republic','region' => 'Asia','currency_code' => 'LAK','currency_name' => 'Lao kip','calling_code' => '856'],
          ['code' => 'LVA','name' => 'Latvia','region' => 'Europe','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '371'],
          ['code' => 'LBN','name' => 'Lebanon','region' => 'Asia','currency_code' => 'LBP','currency_name' => 'Lebanese pound','calling_code' => '961'],
          ['code' => 'LSO','name' => 'Lesotho','region' => 'Africa','currency_code' => 'LSL','currency_name' => 'Lesotho loti','calling_code' => '266'],
          ['code' => 'LBR','name' => 'Liberia','region' => 'Africa','currency_code' => 'LRD','currency_name' => 'Liberian dollar','calling_code' => '231'],
          ['code' => 'LBY','name' => 'Libya','region' => 'Africa','currency_code' => 'LYD','currency_name' => 'Libyan dinar','calling_code' => '218'],
          ['code' => 'LIE','name' => 'Liechtenstein','region' => 'Europe','currency_code' => 'CHF','currency_name' => 'Swiss franc','calling_code' => '423'],
          ['code' => 'LTU','name' => 'Lithuania','region' => 'Europe','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '370'],
          ['code' => 'LUX','name' => 'Luxembourg','region' => 'Europe','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '352'],
          ['code' => 'MAC','name' => 'Macao','region' => 'Asia','currency_code' => 'MOP','currency_name' => 'Macanese pataca','calling_code' => '853'],
          ['code' => 'MKD','name' => 'Macedonia (the former Yugoslav Republic of)','region' => 'Europe','currency_code' => 'MKD','currency_name' => 'Macedonian denar','calling_code' => '389'],
          ['code' => 'MDG','name' => 'Madagascar','region' => 'Africa','currency_code' => 'MGA','currency_name' => 'Malagasy ariary','calling_code' => '261'],
          ['code' => 'MWI','name' => 'Malawi','region' => 'Africa','currency_code' => 'MWK','currency_name' => 'Malawian kwacha','calling_code' => '265'],
          ['code' => 'MYS','name' => 'Malaysia','region' => 'Asia','currency_code' => 'MYR','currency_name' => 'Malaysian ringgit','calling_code' => '60'],
          ['code' => 'MDV','name' => 'Maldives','region' => 'Asia','currency_code' => 'MVR','currency_name' => 'Maldivian rufiyaa','calling_code' => '960'],
          ['code' => 'MLI','name' => 'Mali','region' => 'Africa','currency_code' => 'XOF','currency_name' => 'West African CFA franc','calling_code' => '223'],
          ['code' => 'MLT','name' => 'Malta','region' => 'Europe','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '356'],
          ['code' => 'MHL','name' => 'Marshall Islands','region' => 'Oceania','currency_code' => 'USD','currency_name' => 'United States dollar','calling_code' => '692'],
          ['code' => 'MTQ','name' => 'Martinique','region' => 'Americas','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '596'],
          ['code' => 'MRT','name' => 'Mauritania','region' => 'Africa','currency_code' => 'MRO','currency_name' => 'Mauritanian ouguiya','calling_code' => '222'],
          ['code' => 'MUS','name' => 'Mauritius','region' => 'Africa','currency_code' => 'MUR','currency_name' => 'Mauritian rupee','calling_code' => '230'],
          ['code' => 'MYT','name' => 'Mayotte','region' => 'Africa','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '262'],
          ['code' => 'MEX','name' => 'Mexico','region' => 'Americas','currency_code' => 'MXN','currency_name' => 'Mexican peso','calling_code' => '52'],
          ['code' => 'FSM','name' => 'Micronesia (Federated States of)','region' => 'Oceania','currency_code' => NULL,'currency_name' => '[D]','calling_code' => '691'],
          ['code' => 'MDA','name' => 'Moldova (Republic of)','region' => 'Europe','currency_code' => 'MDL','currency_name' => 'Moldovan leu','calling_code' => '373'],
          ['code' => 'MCO','name' => 'Monaco','region' => 'Europe','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '377'],
          ['code' => 'MNG','name' => 'Mongolia','region' => 'Asia','currency_code' => 'MNT','currency_name' => 'Mongolian tögrög','calling_code' => '976'],
          ['code' => 'MNE','name' => 'Montenegro','region' => 'Europe','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '382'],
          ['code' => 'MSR','name' => 'Montserrat','region' => 'Americas','currency_code' => 'XCD','currency_name' => 'East Caribbean dollar','calling_code' => '1664'],
          ['code' => 'MAR','name' => 'Morocco','region' => 'Africa','currency_code' => 'MAD','currency_name' => 'Moroccan dirham','calling_code' => '212'],
          ['code' => 'MOZ','name' => 'Mozambique','region' => 'Africa','currency_code' => 'MZN','currency_name' => 'Mozambican metical','calling_code' => '258'],
          ['code' => 'MMR','name' => 'Myanmar','region' => 'Asia','currency_code' => 'MMK','currency_name' => 'Burmese kyat','calling_code' => '95'],
          ['code' => 'NAM','name' => 'Namibia','region' => 'Africa','currency_code' => 'NAD','currency_name' => 'Namibian dollar','calling_code' => '264'],
          ['code' => 'NRU','name' => 'Nauru','region' => 'Oceania','currency_code' => 'AUD','currency_name' => 'Australian dollar','calling_code' => '674'],
          ['code' => 'NPL','name' => 'Nepal','region' => 'Asia','currency_code' => 'NPR','currency_name' => 'Nepalese rupee','calling_code' => '977'],
          ['code' => 'NLD','name' => 'Netherlands','region' => 'Europe','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '31'],
          ['code' => 'NCL','name' => 'New Caledonia','region' => 'Oceania','currency_code' => 'XPF','currency_name' => 'CFP franc','calling_code' => '687'],
          ['code' => 'NZL','name' => 'New Zealand','region' => 'Oceania','currency_code' => 'NZD','currency_name' => 'New Zealand dollar','calling_code' => '64'],
          ['code' => 'NIC','name' => 'Nicaragua','region' => 'Americas','currency_code' => 'NIO','currency_name' => 'Nicaraguan córdoba','calling_code' => '505'],
          ['code' => 'NER','name' => 'Niger','region' => 'Africa','currency_code' => 'XOF','currency_name' => 'West African CFA franc','calling_code' => '227'],
          ['code' => 'NGA','name' => 'Nigeria','region' => 'Africa','currency_code' => 'NGN','currency_name' => 'Nigerian naira','calling_code' => '234'],
          ['code' => 'NIU','name' => 'Niue','region' => 'Oceania','currency_code' => 'NZD','currency_name' => 'New Zealand dollar','calling_code' => '683'],
          ['code' => 'NFK','name' => 'Norfolk Island','region' => 'Oceania','currency_code' => 'AUD','currency_name' => 'Australian dollar','calling_code' => '672'],
          ['code' => 'PRK','name' => 'Korea (Democratic People\'s Republic of)','region' => 'Asia','currency_code' => 'KPW','currency_name' => 'North Korean won','calling_code' => '850'],
          ['code' => 'MNP','name' => 'Northern Mariana Islands','region' => 'Oceania','currency_code' => 'USD','currency_name' => 'United States dollar','calling_code' => '1670'],
          ['code' => 'NOR','name' => 'Norway','region' => 'Europe','currency_code' => 'NOK','currency_name' => 'Norwegian krone','calling_code' => '47'],
          ['code' => 'OMN','name' => 'Oman','region' => 'Asia','currency_code' => 'OMR','currency_name' => 'Omani rial','calling_code' => '968'],
          ['code' => 'PAK','name' => 'Pakistan','region' => 'Asia','currency_code' => 'PKR','currency_name' => 'Pakistani rupee','calling_code' => '92'],
          ['code' => 'PLW','name' => 'Palau','region' => 'Oceania','currency_code' => '(none)','currency_name' => '[E]','calling_code' => '680'],
          ['code' => 'PSE','name' => 'Palestine, State of','region' => 'Asia','currency_code' => 'ILS','currency_name' => 'Israeli new sheqel','calling_code' => '970'],
          ['code' => 'PAN','name' => 'Panama','region' => 'Americas','currency_code' => 'PAB','currency_name' => 'Panamanian balboa','calling_code' => '507'],
          ['code' => 'PNG','name' => 'Papua New Guinea','region' => 'Oceania','currency_code' => 'PGK','currency_name' => 'Papua New Guinean kina','calling_code' => '675'],
          ['code' => 'PRY','name' => 'Paraguay','region' => 'Americas','currency_code' => 'PYG','currency_name' => 'Paraguayan guaraní','calling_code' => '595'],
          ['code' => 'PER','name' => 'Peru','region' => 'Americas','currency_code' => 'PEN','currency_name' => 'Peruvian sol','calling_code' => '51'],
          ['code' => 'PHL','name' => 'Philippines','region' => 'Asia','currency_code' => 'PHP','currency_name' => 'Philippine peso','calling_code' => '63'],
          ['code' => 'PCN','name' => 'Pitcairn','region' => 'Oceania','currency_code' => 'NZD','currency_name' => 'New Zealand dollar','calling_code' => '64'],
          ['code' => 'POL','name' => 'Poland','region' => 'Europe','currency_code' => 'PLN','currency_name' => 'Polish złoty','calling_code' => '48'],
          ['code' => 'PRT','name' => 'Portugal','region' => 'Europe','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '351'],
          ['code' => 'PRI','name' => 'Puerto Rico','region' => 'Americas','currency_code' => 'USD','currency_name' => 'United States dollar','calling_code' => '1787'],
          ['code' => 'QAT','name' => 'Qatar','region' => 'Asia','currency_code' => 'QAR','currency_name' => 'Qatari riyal','calling_code' => '974'],
          ['code' => 'KOS','name' => 'Republic of Kosovo','region' => 'Europe','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '383'],
          ['code' => 'REU','name' => 'Réunion','region' => 'Africa','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '262'],
          ['code' => 'ROU','name' => 'Romania','region' => 'Europe','currency_code' => 'RON','currency_name' => 'Romanian leu','calling_code' => '40'],
          ['code' => 'RUS','name' => 'Russian Federation','region' => 'Europe','currency_code' => 'RUB','currency_name' => 'Russian ruble','calling_code' => '7'],
          ['code' => 'RWA','name' => 'Rwanda','region' => 'Africa','currency_code' => 'RWF','currency_name' => 'Rwandan franc','calling_code' => '250'],
          ['code' => 'BLM','name' => 'Saint Barthélemy','region' => 'Americas','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '590'],
          ['code' => 'SHN','name' => 'Saint Helena, Ascension and Tristan da Cunha','region' => 'Africa','currency_code' => 'SHP','currency_name' => 'Saint Helena pound','calling_code' => '290'],
          ['code' => 'KNA','name' => 'Saint Kitts and Nevis','region' => 'Americas','currency_code' => 'XCD','currency_name' => 'East Caribbean dollar','calling_code' => '1869'],
          ['code' => 'LCA','name' => 'Saint Lucia','region' => 'Americas','currency_code' => 'XCD','currency_name' => 'East Caribbean dollar','calling_code' => '1758'],
          ['code' => 'MAF','name' => 'Saint Martin (French part)','region' => 'Americas','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '590'],
          ['code' => 'SPM','name' => 'Saint Pierre and Miquelon','region' => 'Americas','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '508'],
          ['code' => 'VCT','name' => 'Saint Vincent and the Grenadines','region' => 'Americas','currency_code' => 'XCD','currency_name' => 'East Caribbean dollar','calling_code' => '1784'],
          ['code' => 'WSM','name' => 'Samoa','region' => 'Oceania','currency_code' => 'WST','currency_name' => 'Samoan tālā','calling_code' => '685'],
          ['code' => 'SMR','name' => 'San Marino','region' => 'Europe','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '378'],
          ['code' => 'STP','name' => 'Sao Tome and Principe','region' => 'Africa','currency_code' => 'STD','currency_name' => 'São Tomé and Príncipe dobra','calling_code' => '239'],
          ['code' => 'SAU','name' => 'Saudi Arabia','region' => 'Asia','currency_code' => 'SAR','currency_name' => 'Saudi riyal','calling_code' => '966'],
          ['code' => 'SEN','name' => 'Senegal','region' => 'Africa','currency_code' => 'XOF','currency_name' => 'West African CFA franc','calling_code' => '221'],
          ['code' => 'SRB','name' => 'Serbia','region' => 'Europe','currency_code' => 'RSD','currency_name' => 'Serbian dinar','calling_code' => '381'],
          ['code' => 'SYC','name' => 'Seychelles','region' => 'Africa','currency_code' => 'SCR','currency_name' => 'Seychellois rupee','calling_code' => '248'],
          ['code' => 'SLE','name' => 'Sierra Leone','region' => 'Africa','currency_code' => 'SLL','currency_name' => 'Sierra Leonean leone','calling_code' => '232'],
          ['code' => 'SGP','name' => 'Singapore','region' => 'Asia','currency_code' => 'BND','currency_name' => 'Brunei dollar','calling_code' => '65'],
          ['code' => 'SXM','name' => 'Sint Maarten (Dutch part)','region' => 'Americas','currency_code' => 'ANG','currency_name' => 'Netherlands Antillean guilder','calling_code' => '1721'],
          ['code' => 'SVK','name' => 'Slovakia','region' => 'Europe','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '421'],
          ['code' => 'SVN','name' => 'Slovenia','region' => 'Europe','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '386'],
          ['code' => 'SLB','name' => 'Solomon Islands','region' => 'Oceania','currency_code' => 'SBD','currency_name' => 'Solomon Islands dollar','calling_code' => '677'],
          ['code' => 'SOM','name' => 'Somalia','region' => 'Africa','currency_code' => 'SOS','currency_name' => 'Somali shilling','calling_code' => '252'],
          ['code' => 'ZAF','name' => 'South Africa','region' => 'Africa','currency_code' => 'ZAR','currency_name' => 'South African rand','calling_code' => '27'],
          ['code' => 'SGS','name' => 'South Georgia and the South Sandwich Islands','region' => 'Americas','currency_code' => 'GBP','currency_name' => 'British pound','calling_code' => '500'],
          ['code' => 'KOR','name' => 'Korea (Republic of)','region' => 'Asia','currency_code' => 'KRW','currency_name' => 'South Korean won','calling_code' => '82'],
          ['code' => 'SSD','name' => 'South Sudan','region' => 'Africa','currency_code' => 'SSP','currency_name' => 'South Sudanese pound','calling_code' => '211'],
          ['code' => 'ESP','name' => 'Spain','region' => 'Europe','currency_code' => 'EUR','currency_name' => 'Euro','calling_code' => '34'],
          ['code' => 'LKA','name' => 'Sri Lanka','region' => 'Asia','currency_code' => 'LKR','currency_name' => 'Sri Lankan rupee','calling_code' => '94'],
          ['code' => 'SDN','name' => 'Sudan','region' => 'Africa','currency_code' => 'SDG','currency_name' => 'Sudanese pound','calling_code' => '249'],
          ['code' => 'SUR','name' => 'Suriname','region' => 'Americas','currency_code' => 'SRD','currency_name' => 'Surinamese dollar','calling_code' => '597'],
          ['code' => 'SJM','name' => 'Svalbard and Jan Mayen','region' => 'Europe','currency_code' => 'NOK','currency_name' => 'Norwegian krone','calling_code' => '4779'],
          ['code' => 'SWZ','name' => 'Swaziland','region' => 'Africa','currency_code' => 'SZL','currency_name' => 'Swazi lilangeni','calling_code' => '268'],
          ['code' => 'SWE','name' => 'Sweden','region' => 'Europe','currency_code' => 'SEK','currency_name' => 'Swedish krona','calling_code' => '46'],
          ['code' => 'CHE','name' => 'Switzerland','region' => 'Europe','currency_code' => 'CHF','currency_name' => 'Swiss franc','calling_code' => '41'],
          ['code' => 'SYR','name' => 'Syrian Arab Republic','region' => 'Asia','currency_code' => 'SYP','currency_name' => 'Syrian pound','calling_code' => '963'],
          ['code' => 'TWN','name' => 'Taiwan','region' => 'Asia','currency_code' => 'TWD','currency_name' => 'New Taiwan dollar','calling_code' => '886'],
          ['code' => 'TJK','name' => 'Tajikistan','region' => 'Asia','currency_code' => 'TJS','currency_name' => 'Tajikistani somoni','calling_code' => '992'],
          ['code' => 'TZA','name' => 'Tanzania, United Republic of','region' => 'Africa','currency_code' => 'TZS','currency_name' => 'Tanzanian shilling','calling_code' => '255'],
          ['code' => 'THA','name' => 'Thailand','region' => 'Asia','currency_code' => 'THB','currency_name' => 'Thai baht','calling_code' => '66'],
          ['code' => 'TLS','name' => 'Timor-Leste','region' => 'Asia','currency_code' => 'USD','currency_name' => 'United States dollar','calling_code' => '670'],
          ['code' => 'TGO','name' => 'Togo','region' => 'Africa','currency_code' => 'XOF','currency_name' => 'West African CFA franc','calling_code' => '228'],
          ['code' => 'TKL','name' => 'Tokelau','region' => 'Oceania','currency_code' => 'NZD','currency_name' => 'New Zealand dollar','calling_code' => '690'],
          ['code' => 'TON','name' => 'Tonga','region' => 'Oceania','currency_code' => 'TOP','currency_name' => 'Tongan paʻanga','calling_code' => '676'],
          ['code' => 'TTO','name' => 'Trinidad and Tobago','region' => 'Americas','currency_code' => 'TTD','currency_name' => 'Trinidad and Tobago dollar','calling_code' => '1868'],
          ['code' => 'TUN','name' => 'Tunisia','region' => 'Africa','currency_code' => 'TND','currency_name' => 'Tunisian dinar','calling_code' => '216'],
          ['code' => 'TUR','name' => 'Turkey','region' => 'Asia','currency_code' => 'TRY','currency_name' => 'Turkish lira','calling_code' => '90'],
          ['code' => 'TKM','name' => 'Turkmenistan','region' => 'Asia','currency_code' => 'TMT','currency_name' => 'Turkmenistan manat','calling_code' => '993'],
          ['code' => 'TCA','name' => 'Turks and Caicos Islands','region' => 'Americas','currency_code' => 'USD','currency_name' => 'United States dollar','calling_code' => '1649'],
          ['code' => 'TUV','name' => 'Tuvalu','region' => 'Oceania','currency_code' => 'AUD','currency_name' => 'Australian dollar','calling_code' => '688'],
          ['code' => 'UGA','name' => 'Uganda','region' => 'Africa','currency_code' => 'UGX','currency_name' => 'Ugandan shilling','calling_code' => '256'],
          ['code' => 'UKR','name' => 'Ukraine','region' => 'Europe','currency_code' => 'UAH','currency_name' => 'Ukrainian hryvnia','calling_code' => '380'],
          ['code' => 'ARE','name' => 'United Arab Emirates','region' => 'Asia','currency_code' => 'AED','currency_name' => 'United Arab Emirates dirham','calling_code' => '971'],
          ['code' => 'GBR','name' => 'United Kingdom of Great Britain and Northern Ireland','region' => 'Europe','currency_code' => 'GBP','currency_name' => 'British pound','calling_code' => '44'],
          ['code' => 'USA','name' => 'United States of America','region' => 'Americas','currency_code' => 'USD','currency_name' => 'United States dollar','calling_code' => '1'],
          ['code' => 'URY','name' => 'Uruguay','region' => 'Americas','currency_code' => 'UYU','currency_name' => 'Uruguayan peso','calling_code' => '598'],
          ['code' => 'UZB','name' => 'Uzbekistan','region' => 'Asia','currency_code' => 'UZS','currency_name' => 'Uzbekistani so\'m','calling_code' => '998'],
          ['code' => 'VUT','name' => 'Vanuatu','region' => 'Oceania','currency_code' => 'VUV','currency_name' => 'Vanuatu vatu','calling_code' => '678'],
          ['code' => 'VEN','name' => 'Venezuela (Bolivarian Republic of)','region' => 'Americas','currency_code' => 'VEF','currency_name' => 'Venezuelan bolívar','calling_code' => '58'],
          ['code' => 'VNM','name' => 'Viet Nam','region' => 'Asia','currency_code' => 'VND','currency_name' => 'Vietnamese đồng','calling_code' => '84'],
          ['code' => 'WLF','name' => 'Wallis and Futuna','region' => 'Oceania','currency_code' => 'XPF','currency_name' => 'CFP franc','calling_code' => '681'],
          ['code' => 'ESH','name' => 'Western Sahara','region' => 'Africa','currency_code' => 'MAD','currency_name' => 'Moroccan dirham','calling_code' => '212'],
          ['code' => 'YEM','name' => 'Yemen','region' => 'Asia','currency_code' => 'YER','currency_name' => 'Yemeni rial','calling_code' => '967'],
          ['code' => 'ZMB','name' => 'Zambia','region' => 'Africa','currency_code' => 'ZMW','currency_name' => 'Zambian kwacha','calling_code' => '260'],
          ['code' => 'ZWE','name' => 'Zimbabwe','region' => 'Africa','currency_code' => 'BWP','currency_name' => 'Botswana pula','calling_code' => '263']
      ];

      foreach ($countries as $country) {
          Country::create(array_merge($country, [
              'created_at' => Carbon::now(),
              'updated_at' => Carbon::now()
          ]));
      };
  }
}
