<?php

use App\Models\Country;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    $data = [
      [
        'name' => 'INDONESIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'ALBANIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'ALGERIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'AMERICAN SAMOA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'ANDORRA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'ANGOLA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'ANGUILLA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'ANTARCTICA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'ANTIGUA AND BARBUDA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'ARGENTINA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'ARMENIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'ARUBA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'AUSTRALIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'AUSTRIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'AZERBAIJAN',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'BAHAMAS',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'BAHRAIN',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'BANGLADESH',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'BARBADOS',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'BELARUS',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'BELGIUM',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'BELIZE',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'BENIN',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'BERMUDA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'BHUTAN',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'BOLIVIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'BOSNIA AND HERZEGOVINA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'BOTSWANA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'BOUVET ISLAND',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'BRAZIL',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'BRITISH INDIAN OCEAN TERRITORY',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'BRUNEI DARUSSALAM',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'BULGARIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'BURKINA FASO',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'BURUNDI',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'CAMBODIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'CAMEROON',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'CANADA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'CAPE VERDE',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'CAYMAN ISLANDS',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'CENTRAL AFRICAN REPUBLIC',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'CHAD',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'CHILE',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'CHINA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'CHRISTMAS ISLAND',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'COCOS (KEELING) ISLANDS',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'COLOMBIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'COMOROS',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'CONGO',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'COOK',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'COSTA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'COTE D\'IVOIRE',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'CROATIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'CUBA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'CYPRUS',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'CZECH REPUBLIC',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'DENMARK',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'DJIBOUTI',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'DOMINICA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'DOMINICAN REPUBLIC',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'ECUADOR',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'EGYPT',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'EL SALVADOR',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'EQUATORIAL GUINEA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'ERITREA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'ESTONIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'ETHIOPIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'FALKLAND ISLANDS (MALVINAS)',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'FAROE ISLANDS',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'FIJI',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'FINLAND',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'FRANCE',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'FRENCH GUIANA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'FRENCH POLYNESIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'FRENCH SOUTHERN TERRITORIES',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'GABON',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'GAMBIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'GEORGIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'GERMANY',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'GHANA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'GIBRALTAR',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'GREECE',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'GREENLAND',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'GRENADA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'GUADELOUPE',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'GUAM',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'GUATEMALA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'GUINEA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'GUINEA-BISSAU',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'GUYANA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'HAITI',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'HEARD ISLAND AND MCDONALD ISLANDS',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'HOLY SEE (VATICAN CITY STATE)',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'HONDURAS',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'HONG KONG',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'HUNGARY',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'ICELAND',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'INDIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'AFGHANISTAN',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'IRAN, ISLAMIC REPUBLIC OF',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'IRAQ',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'IRELAND',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'ISRAEL',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'ITALY',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'JAMAICA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'JAPAN',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'JORDAN',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'KAZAKHSTAN',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'KENYA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'KIRIBATI',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'KOREA, REPUBLIC OF',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'KUWAIT',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'KYRGYZSTAN',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'LATVIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'LEBANON',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'LESOTHO',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'LIBERIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'LIBYAN ARAB JAMAHIRIYA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'LIECHTENSTEIN',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'LITHUANIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'LUXEMBOURG',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'MACAO',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'MADAGASCAR',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'MALAWI',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'MALAYSIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'MALDIVES',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'MALI',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'MALTA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'MARSHALL ISLANDS',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'MARTINIQUE',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'MAURITANIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'MAURITIUS',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'MAYOTTE',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'MEXICO',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'MICRONESIA, FEDERATED STATES OF',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'MOLDOVA, REPUBLIC OF',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'MONACO',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'MONGOLIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'MONTSERRAT',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'MOROCCO',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'MOZAMBIQUE',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'MYANMAR',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'NAMIBIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'NAURU',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'NEPAL',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'NETHERLANDS',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'NETHERLANDS ANTILLES',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'NEW CALEDONIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'NEW ZEALAND',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'NICARAGUA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'NIGER',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'NIGERIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'NIUE',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'NORFOLK ISLAND',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'NORTHERN MARIANA ISLANDS',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'NORWAY',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'OMAN',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'PAKISTAN',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'PALAU',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'PALESTINIAN TERRITORY, OCCUPIED',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'PANAMA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'PAPUA NEW GUINEA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'PARAGUAY',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'PERU',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'PHILIPPINES',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'PITCAIRN',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'POLAND',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'PORTUGAL',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'PUERTO RICO',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'QATAR',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'REUNION',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'ROMANIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'RUSSIAN FEDERATION',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'RWANDA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SAINT HELENA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SAINT KITTS AND NEVIS',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SAINT LUCIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SAINT PIERRE AND MIQUELON',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SAINT VINCENT AND THE GRENADINES',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SAMOA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SAN MARINO',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SAO TOME AND PRINCIPE',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SAUDI ARABIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SENEGAL',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SERBIA AND MONTENEGRO',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SEYCHELLES',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SIERRA \LEONE',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SINGAPORE',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SLOVAKIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SLOVENIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SOLOMON ISLANDS',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SOMALIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SOUTH AFRICA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SPAIN',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SRI LANKA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SUDAN',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SURINAME',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SVALBARD AND JAN MAYEN',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SWAZILAND',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SWEDEN',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SWITZERLAND',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'SYRIAN ARAB REPUBLIC',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'TAIWAN, PROVINCE OF CHINA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'TAJIKISTAN',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'TANZANIA, UNITED REPUBLIC OF',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'THAILAND',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'TIMOR-LESTE',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'TOGO',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'TOKELAU',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'TONGA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'TRINIDAD AND TOBAGO',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'TUNISIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'TURKEY',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'TURKMENISTAN',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'TURKS AND CAICOS ISLANDS',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'TUVALU',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'UGANDA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'UKRAINE',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'UNITED ARAB EMIRATES',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'UNITED KINGDOM',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'UNITED STATES',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'UNITED STATES MINOR OUTLYING ISLANDS',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'URUGUAY',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'UZBEKISTAN',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'VANUATU',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'VENEZUELA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'VIET NAM',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'VIRGIN ISLANDS, BRITISH',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'VIRGIN ISLANDS, U.S.',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'WALLIS AND FUTUNA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'WESTERN SAHARA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'YEMEN',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'ZAMBIA',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ],
      [
        'name' => 'ZIMBABWE',
        'currency_code' => NULL,
        'currency_name' => NULL,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
      ]
    ];

    Country::insert($data);
  }
}
