<?php

use App\Models\Country;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
      $countries = [
          ['code' => 'IDN', 'name' => 'Indonesia', 'region' => 'Asia', 'currency_code' => 'IDR', 'currency_name' => 'Indonesian rupiah'],
          ['code' => 'AFG', 'name' => 'Afghanistan', 'region' => 'Asia', 'currency_code' => 'AFN', 'currency_name' => 'Afghan afghani'],
          ['code' => 'ALA', 'name' => 'Åland Islands', 'region' => 'Europe', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'ALB', 'name' => 'Albania', 'region' => 'Europe', 'currency_code' => 'ALL', 'currency_name' => 'Albanian lek'],
          ['code' => 'DZA', 'name' => 'Algeria', 'region' => 'Africa', 'currency_code' => 'DZD', 'currency_name' => 'Algerian dinar'],
          ['code' => 'ASM', 'name' => 'American Samoa', 'region' => 'Oceania', 'currency_code' => 'USD', 'currency_name' => 'United State Dollar'],
          ['code' => 'AND', 'name' => 'Andorra', 'region' => 'Europe', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'AGO', 'name' => 'Angola', 'region' => 'Africa', 'currency_code' => 'AOA', 'currency_name' => 'Angolan kwanza'],
          ['code' => 'AIA', 'name' => 'Anguilla', 'region' => 'Americas', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean dollar'],
          ['code' => 'ATA', 'name' => 'Antarctica', 'region' => 'Polar', 'currency_code' => 'AUD', 'currency_name' => 'Australian dollar'],
          ['code' => 'ATG', 'name' => 'Antigua and Barbuda', 'region' => 'Americas', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean dollar'],
          ['code' => 'ARG', 'name' => 'Argentina', 'region' => 'Americas', 'currency_code' => 'ARS', 'currency_name' => 'Argentine peso'],
          ['code' => 'ARM', 'name' => 'Armenia', 'region' => 'Asia', 'currency_code' => 'AMD', 'currency_name' => 'Armenian dram'],
          ['code' => 'ABW', 'name' => 'Aruba', 'region' => 'Americas', 'currency_code' => 'AWG', 'currency_name' => 'Aruban florin'],
          ['code' => 'AUS', 'name' => 'Australia', 'region' => 'Oceania', 'currency_code' => 'AUD', 'currency_name' => 'Australian dollar'],
          ['code' => 'AUT', 'name' => 'Austria', 'region' => 'Europe', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'AZE', 'name' => 'Azerbaijan', 'region' => 'Asia', 'currency_code' => 'AZN', 'currency_name' => 'Azerbaijani manat'],
          ['code' => 'BHS', 'name' => 'Bahamas', 'region' => 'Americas', 'currency_code' => 'BSD', 'currency_name' => 'Bahamian dollar'],
          ['code' => 'BHR', 'name' => 'Bahrain', 'region' => 'Asia', 'currency_code' => 'BHD', 'currency_name' => 'Bahraini dinar'],
          ['code' => 'BGD', 'name' => 'Bangladesh', 'region' => 'Asia', 'currency_code' => 'BDT', 'currency_name' => 'Bangladeshi taka'],
          ['code' => 'BRB', 'name' => 'Barbados', 'region' => 'Americas', 'currency_code' => 'BBD', 'currency_name' => 'Barbadian dollar'],
          ['code' => 'BLR', 'name' => 'Belarus', 'region' => 'Europe', 'currency_code' => 'BYN', 'currency_name' => 'New Belarusian ruble'],
          ['code' => 'BEL', 'name' => 'Belgium', 'region' => 'Europe', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'BLZ', 'name' => 'Belize', 'region' => 'Americas', 'currency_code' => 'BZD', 'currency_name' => 'Belize dollar'],
          ['code' => 'BEN', 'name' => 'Benin', 'region' => 'Africa', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA franc'],
          ['code' => 'BMU', 'name' => 'Bermuda', 'region' => 'Americas', 'currency_code' => 'BMD', 'currency_name' => 'Bermudian dollar'],
          ['code' => 'BTN', 'name' => 'Bhutan', 'region' => 'Asia', 'currency_code' => 'BTN', 'currency_name' => 'Bhutanese ngultrum'],
          ['code' => 'BOL', 'name' => 'Bolivia (Plurinational State of)', 'region' => 'Americas', 'currency_code' => 'BOB', 'currency_name' => 'Bolivian boliviano'],
          ['code' => 'BES', 'name' => 'Bonaire, Sint Eustatius and Saba', 'region' => 'Americas', 'currency_code' => 'USD', 'currency_name' => 'United States dollar'],
          ['code' => 'BIH', 'name' => 'Bosnia and Herzegovina', 'region' => 'Europe', 'currency_code' => 'BAM', 'currency_name' => 'Bosnia and Herzegovina convertible mark'],
          ['code' => 'BWA', 'name' => 'Botswana', 'region' => 'Africa', 'currency_code' => 'BWP', 'currency_name' => 'Botswana pula'],
          ['code' => 'BVT', 'name' => 'Bouvet Island', 'region' => '', 'currency_code' => 'NOK', 'currency_name' => 'Norwegian krone'],
          ['code' => 'BRA', 'name' => 'Brazil', 'region' => 'Americas', 'currency_code' => 'BRL', 'currency_name' => 'Brazilian real'],
          ['code' => 'IOT', 'name' => 'British Indian Ocean Territory', 'region' => 'Africa', 'currency_code' => 'USD', 'currency_name' => 'United States dollar'],
          ['code' => 'UMI', 'name' => 'United States Minor Outlying Islands', 'region' => 'Americas', 'currency_code' => 'USD', 'currency_name' => 'United States Dollar'],
          ['code' => 'VGB', 'name' => 'Virgin Islands (British)', 'region' => 'Americas', 'currency_code' => NULL, 'currency_name' => '[D]'],
          ['code' => 'VIR', 'name' => 'Virgin Islands (U.S.)', 'region' => 'Americas', 'currency_code' => 'USD', 'currency_name' => 'United States dollar'],
          ['code' => 'BRN', 'name' => 'Brunei Darussalam', 'region' => 'Asia', 'currency_code' => 'BND', 'currency_name' => 'Brunei dollar'],
          ['code' => 'BGR', 'name' => 'Bulgaria', 'region' => 'Europe', 'currency_code' => 'BGN', 'currency_name' => 'Bulgarian lev'],
          ['code' => 'BFA', 'name' => 'Burkina Faso', 'region' => 'Africa', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA franc'],
          ['code' => 'BDI', 'name' => 'Burundi', 'region' => 'Africa', 'currency_code' => 'BIF', 'currency_name' => 'Burundian franc'],
          ['code' => 'KHM', 'name' => 'Cambodia', 'region' => 'Asia', 'currency_code' => 'KHR', 'currency_name' => 'Cambodian riel'],
          ['code' => 'CMR', 'name' => 'Cameroon', 'region' => 'Africa', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA franc'],
          ['code' => 'CAN', 'name' => 'Canada', 'region' => 'Americas', 'currency_code' => 'CAD', 'currency_name' => 'Canadian dollar'],
          ['code' => 'CPV', 'name' => 'Cabo Verde', 'region' => 'Africa', 'currency_code' => 'CVE', 'currency_name' => 'Cape Verdean escudo'],
          ['code' => 'CYM', 'name' => 'Cayman Islands', 'region' => 'Americas', 'currency_code' => 'KYD', 'currency_name' => 'Cayman Islands dollar'],
          ['code' => 'CAF', 'name' => 'Central African Republic', 'region' => 'Africa', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA franc'],
          ['code' => 'TCD', 'name' => 'Chad', 'region' => 'Africa', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA franc'],
          ['code' => 'CHL', 'name' => 'Chile', 'region' => 'Americas', 'currency_code' => 'CLP', 'currency_name' => 'Chilean peso'],
          ['code' => 'CHN', 'name' => 'China', 'region' => 'Asia', 'currency_code' => 'CNY', 'currency_name' => 'Chinese yuan'],
          ['code' => 'CXR', 'name' => 'Christmas Island', 'region' => 'Oceania', 'currency_code' => 'AUD', 'currency_name' => 'Australian dollar'],
          ['code' => 'CCK', 'name' => 'Cocos (Keeling) Islands', 'region' => 'Oceania', 'currency_code' => 'AUD', 'currency_name' => 'Australian dollar'],
          ['code' => 'COL', 'name' => 'Colombia', 'region' => 'Americas', 'currency_code' => 'COP', 'currency_name' => 'Colombian peso'],
          ['code' => 'COM', 'name' => 'Comoros', 'region' => 'Africa', 'currency_code' => 'KMF', 'currency_name' => 'Comorian franc'],
          ['code' => 'COG', 'name' => 'Congo', 'region' => 'Africa', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA franc'],
          ['code' => 'COD', 'name' => 'Congo (Democratic Republic of the)', 'region' => 'Africa', 'currency_code' => 'CDF', 'currency_name' => 'Congolese franc'],
          ['code' => 'COK', 'name' => 'Cook Islands', 'region' => 'Oceania', 'currency_code' => 'NZD', 'currency_name' => 'New Zealand dollar'],
          ['code' => 'CRI', 'name' => 'Costa Rica', 'region' => 'Americas', 'currency_code' => 'CRC', 'currency_name' => 'Costa Rican colón'],
          ['code' => 'HRV', 'name' => 'Croatia', 'region' => 'Europe', 'currency_code' => 'HRK', 'currency_name' => 'Croatian kuna'],
          ['code' => 'CUB', 'name' => 'Cuba', 'region' => 'Americas', 'currency_code' => 'CUC', 'currency_name' => 'Cuban convertible peso'],
          ['code' => 'CUW', 'name' => 'Curaçao', 'region' => 'Americas', 'currency_code' => 'ANG', 'currency_name' => 'Netherlands Antillean guilder'],
          ['code' => 'CYP', 'name' => 'Cyprus', 'region' => 'Europe', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'CZE', 'name' => 'Czech Republic', 'region' => 'Europe', 'currency_code' => 'CZK', 'currency_name' => 'Czech koruna'],
          ['code' => 'DNK', 'name' => 'Denmark', 'region' => 'Europe', 'currency_code' => 'DKK', 'currency_name' => 'Danish krone'],
          ['code' => 'DJI', 'name' => 'Djibouti', 'region' => 'Africa', 'currency_code' => 'DJF', 'currency_name' => 'Djiboutian franc'],
          ['code' => 'DMA', 'name' => 'Dominica', 'region' => 'Americas', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean dollar'],
          ['code' => 'DOM', 'name' => 'Dominican Republic', 'region' => 'Americas', 'currency_code' => 'DOP', 'currency_name' => 'Dominican peso'],
          ['code' => 'ECU', 'name' => 'Ecuador', 'region' => 'Americas', 'currency_code' => 'USD', 'currency_name' => 'United States dollar'],
          ['code' => 'EGY', 'name' => 'Egypt', 'region' => 'Africa', 'currency_code' => 'EGP', 'currency_name' => 'Egyptian pound'],
          ['code' => 'SLV', 'name' => 'El Salvador', 'region' => 'Americas', 'currency_code' => 'USD', 'currency_name' => 'United States dollar'],
          ['code' => 'GNQ', 'name' => 'Equatorial Guinea', 'region' => 'Africa', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA franc'],
          ['code' => 'ERI', 'name' => 'Eritrea', 'region' => 'Africa', 'currency_code' => 'ERN', 'currency_name' => 'Eritrean nakfa'],
          ['code' => 'EST', 'name' => 'Estonia', 'region' => 'Europe', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'ETH', 'name' => 'Ethiopia', 'region' => 'Africa', 'currency_code' => 'ETB', 'currency_name' => 'Ethiopian birr'],
          ['code' => 'FLK', 'name' => 'Falkland Islands (Malvinas)', 'region' => 'Americas', 'currency_code' => 'FKP', 'currency_name' => 'Falkland Islands pound'],
          ['code' => 'FRO', 'name' => 'Faroe Islands', 'region' => 'Europe', 'currency_code' => 'DKK', 'currency_name' => 'Danish krone'],
          ['code' => 'FJI', 'name' => 'Fiji', 'region' => 'Oceania', 'currency_code' => 'FJD', 'currency_name' => 'Fijian dollar'],
          ['code' => 'FIN', 'name' => 'Finland', 'region' => 'Europe', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'FRA', 'name' => 'France', 'region' => 'Europe', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'GUF', 'name' => 'French Guiana', 'region' => 'Americas', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'PYF', 'name' => 'French Polynesia', 'region' => 'Oceania', 'currency_code' => 'XPF', 'currency_name' => 'CFP franc'],
          ['code' => 'ATF', 'name' => 'French Southern Territories', 'region' => 'Africa', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'GAB', 'name' => 'Gabon', 'region' => 'Africa', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA franc'],
          ['code' => 'GMB', 'name' => 'Gambia', 'region' => 'Africa', 'currency_code' => 'GMD', 'currency_name' => 'Gambian dalasi'],
          ['code' => 'GEO', 'name' => 'Georgia', 'region' => 'Asia', 'currency_code' => 'GEL', 'currency_name' => 'Georgian Lari'],
          ['code' => 'DEU', 'name' => 'Germany', 'region' => 'Europe', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'GHA', 'name' => 'Ghana', 'region' => 'Africa', 'currency_code' => 'GHS', 'currency_name' => 'Ghanaian cedi'],
          ['code' => 'GIB', 'name' => 'Gibraltar', 'region' => 'Europe', 'currency_code' => 'GIP', 'currency_name' => 'Gibraltar pound'],
          ['code' => 'GRC', 'name' => 'Greece', 'region' => 'Europe', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'GRL', 'name' => 'Greenland', 'region' => 'Americas', 'currency_code' => 'DKK', 'currency_name' => 'Danish krone'],
          ['code' => 'GRD', 'name' => 'Grenada', 'region' => 'Americas', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean dollar'],
          ['code' => 'GLP', 'name' => 'Guadeloupe', 'region' => 'Americas', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'GUM', 'name' => 'Guam', 'region' => 'Oceania', 'currency_code' => 'USD', 'currency_name' => 'United States dollar'],
          ['code' => 'GTM', 'name' => 'Guatemala', 'region' => 'Americas', 'currency_code' => 'GTQ', 'currency_name' => 'Guatemalan quetzal'],
          ['code' => 'GGY', 'name' => 'Guernsey', 'region' => 'Europe', 'currency_code' => 'GBP', 'currency_name' => 'British pound'],
          ['code' => 'GIN', 'name' => 'Guinea', 'region' => 'Africa', 'currency_code' => 'GNF', 'currency_name' => 'Guinean franc'],
          ['code' => 'GNB', 'name' => 'Guinea-Bissau', 'region' => 'Africa', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA franc'],
          ['code' => 'GUY', 'name' => 'Guyana', 'region' => 'Americas', 'currency_code' => 'GYD', 'currency_name' => 'Guyanese dollar'],
          ['code' => 'HTI', 'name' => 'Haiti', 'region' => 'Americas', 'currency_code' => 'HTG', 'currency_name' => 'Haitian gourde'],
          ['code' => 'HMD', 'name' => 'Heard Island and McDonald Islands', 'region' => '', 'currency_code' => 'AUD', 'currency_name' => 'Australian dollar'],
          ['code' => 'VAT', 'name' => 'Holy See', 'region' => 'Europe', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'HND', 'name' => 'Honduras', 'region' => 'Americas', 'currency_code' => 'HNL', 'currency_name' => 'Honduran lempira'],
          ['code' => 'HKG', 'name' => 'Hong Kong', 'region' => 'Asia', 'currency_code' => 'HKD', 'currency_name' => 'Hong Kong dollar'],
          ['code' => 'HUN', 'name' => 'Hungary', 'region' => 'Europe', 'currency_code' => 'HUF', 'currency_name' => 'Hungarian forint'],
          ['code' => 'ISL', 'name' => 'Iceland', 'region' => 'Europe', 'currency_code' => 'ISK', 'currency_name' => 'Icelandic króna'],
          ['code' => 'IND', 'name' => 'India', 'region' => 'Asia', 'currency_code' => 'INR', 'currency_name' => 'Indian rupee'],
          ['code' => 'CIV', 'name' => 'Côte d\'Ivoire', 'region' => 'Africa', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA franc'],
          ['code' => 'IRN', 'name' => 'Iran (Islamic Republic of)', 'region' => 'Asia', 'currency_code' => 'IRR', 'currency_name' => 'Iranian rial'],
          ['code' => 'IRQ', 'name' => 'Iraq', 'region' => 'Asia', 'currency_code' => 'IQD', 'currency_name' => 'Iraqi dinar'],
          ['code' => 'IRL', 'name' => 'Ireland', 'region' => 'Europe', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'IMN', 'name' => 'Isle of Man', 'region' => 'Europe', 'currency_code' => 'GBP', 'currency_name' => 'British pound'],
          ['code' => 'ISR', 'name' => 'Israel', 'region' => 'Asia', 'currency_code' => 'ILS', 'currency_name' => 'Israeli new shekel'],
          ['code' => 'ITA', 'name' => 'Italy', 'region' => 'Europe', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'JAM', 'name' => 'Jamaica', 'region' => 'Americas', 'currency_code' => 'JMD', 'currency_name' => 'Jamaican dollar'],
          ['code' => 'JPN', 'name' => 'Japan', 'region' => 'Asia', 'currency_code' => 'JPY', 'currency_name' => 'Japanese yen'],
          ['code' => 'JEY', 'name' => 'Jersey', 'region' => 'Europe', 'currency_code' => 'GBP', 'currency_name' => 'British pound'],
          ['code' => 'JOR', 'name' => 'Jordan', 'region' => 'Asia', 'currency_code' => 'JOD', 'currency_name' => 'Jordanian dinar'],
          ['code' => 'KAZ', 'name' => 'Kazakhstan', 'region' => 'Asia', 'currency_code' => 'KZT', 'currency_name' => 'Kazakhstani tenge'],
          ['code' => 'KEN', 'name' => 'Kenya', 'region' => 'Africa', 'currency_code' => 'KES', 'currency_name' => 'Kenyan shilling'],
          ['code' => 'KIR', 'name' => 'Kiribati', 'region' => 'Oceania', 'currency_code' => 'AUD', 'currency_name' => 'Australian dollar'],
          ['code' => 'KWT', 'name' => 'Kuwait', 'region' => 'Asia', 'currency_code' => 'KWD', 'currency_name' => 'Kuwaiti dinar'],
          ['code' => 'KGZ', 'name' => 'Kyrgyzstan', 'region' => 'Asia', 'currency_code' => 'KGS', 'currency_name' => 'Kyrgyzstani som'],
          ['code' => 'LAO', 'name' => 'Lao People\'s Democratic Republic', 'region' => 'Asia', 'currency_code' => 'LAK', 'currency_name' => 'Lao kip'],
          ['code' => 'LVA', 'name' => 'Latvia', 'region' => 'Europe', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'LBN', 'name' => 'Lebanon', 'region' => 'Asia', 'currency_code' => 'LBP', 'currency_name' => 'Lebanese pound'],
          ['code' => 'LSO', 'name' => 'Lesotho', 'region' => 'Africa', 'currency_code' => 'LSL', 'currency_name' => 'Lesotho loti'],
          ['code' => 'LBR', 'name' => 'Liberia', 'region' => 'Africa', 'currency_code' => 'LRD', 'currency_name' => 'Liberian dollar'],
          ['code' => 'LBY', 'name' => 'Libya', 'region' => 'Africa', 'currency_code' => 'LYD', 'currency_name' => 'Libyan dinar'],
          ['code' => 'LIE', 'name' => 'Liechtenstein', 'region' => 'Europe', 'currency_code' => 'CHF', 'currency_name' => 'Swiss franc'],
          ['code' => 'LTU', 'name' => 'Lithuania', 'region' => 'Europe', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'LUX', 'name' => 'Luxembourg', 'region' => 'Europe', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'MAC', 'name' => 'Macao', 'region' => 'Asia', 'currency_code' => 'MOP', 'currency_name' => 'Macanese pataca'],
          ['code' => 'MKD', 'name' => 'Macedonia (the former Yugoslav Republic of)', 'region' => 'Europe', 'currency_code' => 'MKD', 'currency_name' => 'Macedonian denar'],
          ['code' => 'MDG', 'name' => 'Madagascar', 'region' => 'Africa', 'currency_code' => 'MGA', 'currency_name' => 'Malagasy ariary'],
          ['code' => 'MWI', 'name' => 'Malawi', 'region' => 'Africa', 'currency_code' => 'MWK', 'currency_name' => 'Malawian kwacha'],
          ['code' => 'MYS', 'name' => 'Malaysia', 'region' => 'Asia', 'currency_code' => 'MYR', 'currency_name' => 'Malaysian ringgit'],
          ['code' => 'MDV', 'name' => 'Maldives', 'region' => 'Asia', 'currency_code' => 'MVR', 'currency_name' => 'Maldivian rufiyaa'],
          ['code' => 'MLI', 'name' => 'Mali', 'region' => 'Africa', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA franc'],
          ['code' => 'MLT', 'name' => 'Malta', 'region' => 'Europe', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'MHL', 'name' => 'Marshall Islands', 'region' => 'Oceania', 'currency_code' => 'USD', 'currency_name' => 'United States dollar'],
          ['code' => 'MTQ', 'name' => 'Martinique', 'region' => 'Americas', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'MRT', 'name' => 'Mauritania', 'region' => 'Africa', 'currency_code' => 'MRO', 'currency_name' => 'Mauritanian ouguiya'],
          ['code' => 'MUS', 'name' => 'Mauritius', 'region' => 'Africa', 'currency_code' => 'MUR', 'currency_name' => 'Mauritian rupee'],
          ['code' => 'MYT', 'name' => 'Mayotte', 'region' => 'Africa', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'MEX', 'name' => 'Mexico', 'region' => 'Americas', 'currency_code' => 'MXN', 'currency_name' => 'Mexican peso'],
          ['code' => 'FSM', 'name' => 'Micronesia (Federated States of)', 'region' => 'Oceania', 'currency_code' => NULL, 'currency_name' => '[D]'],
          ['code' => 'MDA', 'name' => 'Moldova (Republic of)', 'region' => 'Europe', 'currency_code' => 'MDL', 'currency_name' => 'Moldovan leu'],
          ['code' => 'MCO', 'name' => 'Monaco', 'region' => 'Europe', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'MNG', 'name' => 'Mongolia', 'region' => 'Asia', 'currency_code' => 'MNT', 'currency_name' => 'Mongolian tögrög'],
          ['code' => 'MNE', 'name' => 'Montenegro', 'region' => 'Europe', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'MSR', 'name' => 'Montserrat', 'region' => 'Americas', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean dollar'],
          ['code' => 'MAR', 'name' => 'Morocco', 'region' => 'Africa', 'currency_code' => 'MAD', 'currency_name' => 'Moroccan dirham'],
          ['code' => 'MOZ', 'name' => 'Mozambique', 'region' => 'Africa', 'currency_code' => 'MZN', 'currency_name' => 'Mozambican metical'],
          ['code' => 'MMR', 'name' => 'Myanmar', 'region' => 'Asia', 'currency_code' => 'MMK', 'currency_name' => 'Burmese kyat'],
          ['code' => 'NAM', 'name' => 'Namibia', 'region' => 'Africa', 'currency_code' => 'NAD', 'currency_name' => 'Namibian dollar'],
          ['code' => 'NRU', 'name' => 'Nauru', 'region' => 'Oceania', 'currency_code' => 'AUD', 'currency_name' => 'Australian dollar'],
          ['code' => 'NPL', 'name' => 'Nepal', 'region' => 'Asia', 'currency_code' => 'NPR', 'currency_name' => 'Nepalese rupee'],
          ['code' => 'NLD', 'name' => 'Netherlands', 'region' => 'Europe', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'NCL', 'name' => 'New Caledonia', 'region' => 'Oceania', 'currency_code' => 'XPF', 'currency_name' => 'CFP franc'],
          ['code' => 'NZL', 'name' => 'New Zealand', 'region' => 'Oceania', 'currency_code' => 'NZD', 'currency_name' => 'New Zealand dollar'],
          ['code' => 'NIC', 'name' => 'Nicaragua', 'region' => 'Americas', 'currency_code' => 'NIO', 'currency_name' => 'Nicaraguan córdoba'],
          ['code' => 'NER', 'name' => 'Niger', 'region' => 'Africa', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA franc'],
          ['code' => 'NGA', 'name' => 'Nigeria', 'region' => 'Africa', 'currency_code' => 'NGN', 'currency_name' => 'Nigerian naira'],
          ['code' => 'NIU', 'name' => 'Niue', 'region' => 'Oceania', 'currency_code' => 'NZD', 'currency_name' => 'New Zealand dollar'],
          ['code' => 'NFK', 'name' => 'Norfolk Island', 'region' => 'Oceania', 'currency_code' => 'AUD', 'currency_name' => 'Australian dollar'],
          ['code' => 'PRK', 'name' => 'Korea (Democratic People\'s Republic of)', 'region' => 'Asia', 'currency_code' => 'KPW', 'currency_name' => 'North Korean won'],
          ['code' => 'MNP', 'name' => 'Northern Mariana Islands', 'region' => 'Oceania', 'currency_code' => 'USD', 'currency_name' => 'United States dollar'],
          ['code' => 'NOR', 'name' => 'Norway', 'region' => 'Europe', 'currency_code' => 'NOK', 'currency_name' => 'Norwegian krone'],
          ['code' => 'OMN', 'name' => 'Oman', 'region' => 'Asia', 'currency_code' => 'OMR', 'currency_name' => 'Omani rial'],
          ['code' => 'PAK', 'name' => 'Pakistan', 'region' => 'Asia', 'currency_code' => 'PKR', 'currency_name' => 'Pakistani rupee'],
          ['code' => 'PLW', 'name' => 'Palau', 'region' => 'Oceania', 'currency_code' => '(none)', 'currency_name' => '[E]'],
          ['code' => 'PSE', 'name' => 'Palestine, State of', 'region' => 'Asia', 'currency_code' => 'ILS', 'currency_name' => 'Israeli new sheqel'],
          ['code' => 'PAN', 'name' => 'Panama', 'region' => 'Americas', 'currency_code' => 'PAB', 'currency_name' => 'Panamanian balboa'],
          ['code' => 'PNG', 'name' => 'Papua New Guinea', 'region' => 'Oceania', 'currency_code' => 'PGK', 'currency_name' => 'Papua New Guinean kina'],
          ['code' => 'PRY', 'name' => 'Paraguay', 'region' => 'Americas', 'currency_code' => 'PYG', 'currency_name' => 'Paraguayan guaraní'],
          ['code' => 'PER', 'name' => 'Peru', 'region' => 'Americas', 'currency_code' => 'PEN', 'currency_name' => 'Peruvian sol'],
          ['code' => 'PHL', 'name' => 'Philippines', 'region' => 'Asia', 'currency_code' => 'PHP', 'currency_name' => 'Philippine peso'],
          ['code' => 'PCN', 'name' => 'Pitcairn', 'region' => 'Oceania', 'currency_code' => 'NZD', 'currency_name' => 'New Zealand dollar'],
          ['code' => 'POL', 'name' => 'Poland', 'region' => 'Europe', 'currency_code' => 'PLN', 'currency_name' => 'Polish złoty'],
          ['code' => 'PRT', 'name' => 'Portugal', 'region' => 'Europe', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'PRI', 'name' => 'Puerto Rico', 'region' => 'Americas', 'currency_code' => 'USD', 'currency_name' => 'United States dollar'],
          ['code' => 'QAT', 'name' => 'Qatar', 'region' => 'Asia', 'currency_code' => 'QAR', 'currency_name' => 'Qatari riyal'],
          ['code' => 'KOS', 'name' => 'Republic of Kosovo', 'region' => 'Europe', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'REU', 'name' => 'Réunion', 'region' => 'Africa', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'ROU', 'name' => 'Romania', 'region' => 'Europe', 'currency_code' => 'RON', 'currency_name' => 'Romanian leu'],
          ['code' => 'RUS', 'name' => 'Russian Federation', 'region' => 'Europe', 'currency_code' => 'RUB', 'currency_name' => 'Russian ruble'],
          ['code' => 'RWA', 'name' => 'Rwanda', 'region' => 'Africa', 'currency_code' => 'RWF', 'currency_name' => 'Rwandan franc'],
          ['code' => 'BLM', 'name' => 'Saint Barthélemy', 'region' => 'Americas', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'SHN', 'name' => 'Saint Helena, Ascension and Tristan da Cunha', 'region' => 'Africa', 'currency_code' => 'SHP', 'currency_name' => 'Saint Helena pound'],
          ['code' => 'KNA', 'name' => 'Saint Kitts and Nevis', 'region' => 'Americas', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean dollar'],
          ['code' => 'LCA', 'name' => 'Saint Lucia', 'region' => 'Americas', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean dollar'],
          ['code' => 'MAF', 'name' => 'Saint Martin (French part)', 'region' => 'Americas', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'SPM', 'name' => 'Saint Pierre and Miquelon', 'region' => 'Americas', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'VCT', 'name' => 'Saint Vincent and the Grenadines', 'region' => 'Americas', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean dollar'],
          ['code' => 'WSM', 'name' => 'Samoa', 'region' => 'Oceania', 'currency_code' => 'WST', 'currency_name' => 'Samoan tālā'],
          ['code' => 'SMR', 'name' => 'San Marino', 'region' => 'Europe', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'STP', 'name' => 'Sao Tome and Principe', 'region' => 'Africa', 'currency_code' => 'STD', 'currency_name' => 'São Tomé and Príncipe dobra'],
          ['code' => 'SAU', 'name' => 'Saudi Arabia', 'region' => 'Asia', 'currency_code' => 'SAR', 'currency_name' => 'Saudi riyal'],
          ['code' => 'SEN', 'name' => 'Senegal', 'region' => 'Africa', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA franc'],
          ['code' => 'SRB', 'name' => 'Serbia', 'region' => 'Europe', 'currency_code' => 'RSD', 'currency_name' => 'Serbian dinar'],
          ['code' => 'SYC', 'name' => 'Seychelles', 'region' => 'Africa', 'currency_code' => 'SCR', 'currency_name' => 'Seychellois rupee'],
          ['code' => 'SLE', 'name' => 'Sierra Leone', 'region' => 'Africa', 'currency_code' => 'SLL', 'currency_name' => 'Sierra Leonean leone'],
          ['code' => 'SGP', 'name' => 'Singapore', 'region' => 'Asia', 'currency_code' => 'BND', 'currency_name' => 'Brunei dollar'],
          ['code' => 'SXM', 'name' => 'Sint Maarten (Dutch part)', 'region' => 'Americas', 'currency_code' => 'ANG', 'currency_name' => 'Netherlands Antillean guilder'],
          ['code' => 'SVK', 'name' => 'Slovakia', 'region' => 'Europe', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'SVN', 'name' => 'Slovenia', 'region' => 'Europe', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'SLB', 'name' => 'Solomon Islands', 'region' => 'Oceania', 'currency_code' => 'SBD', 'currency_name' => 'Solomon Islands dollar'],
          ['code' => 'SOM', 'name' => 'Somalia', 'region' => 'Africa', 'currency_code' => 'SOS', 'currency_name' => 'Somali shilling'],
          ['code' => 'ZAF', 'name' => 'South Africa', 'region' => 'Africa', 'currency_code' => 'ZAR', 'currency_name' => 'South African rand'],
          ['code' => 'SGS', 'name' => 'South Georgia and the South Sandwich Islands', 'region' => 'Americas', 'currency_code' => 'GBP', 'currency_name' => 'British pound'],
          ['code' => 'KOR', 'name' => 'Korea (Republic of)', 'region' => 'Asia', 'currency_code' => 'KRW', 'currency_name' => 'South Korean won'],
          ['code' => 'SSD', 'name' => 'South Sudan', 'region' => 'Africa', 'currency_code' => 'SSP', 'currency_name' => 'South Sudanese pound'],
          ['code' => 'ESP', 'name' => 'Spain', 'region' => 'Europe', 'currency_code' => 'EUR', 'currency_name' => 'Euro'],
          ['code' => 'LKA', 'name' => 'Sri Lanka', 'region' => 'Asia', 'currency_code' => 'LKR', 'currency_name' => 'Sri Lankan rupee'],
          ['code' => 'SDN', 'name' => 'Sudan', 'region' => 'Africa', 'currency_code' => 'SDG', 'currency_name' => 'Sudanese pound'],
          ['code' => 'SUR', 'name' => 'Suriname', 'region' => 'Americas', 'currency_code' => 'SRD', 'currency_name' => 'Surinamese dollar'],
          ['code' => 'SJM', 'name' => 'Svalbard and Jan Mayen', 'region' => 'Europe', 'currency_code' => 'NOK', 'currency_name' => 'Norwegian krone'],
          ['code' => 'SWZ', 'name' => 'Swaziland', 'region' => 'Africa', 'currency_code' => 'SZL', 'currency_name' => 'Swazi lilangeni'],
          ['code' => 'SWE', 'name' => 'Sweden', 'region' => 'Europe', 'currency_code' => 'SEK', 'currency_name' => 'Swedish krona'],
          ['code' => 'CHE', 'name' => 'Switzerland', 'region' => 'Europe', 'currency_code' => 'CHF', 'currency_name' => 'Swiss franc'],
          ['code' => 'SYR', 'name' => 'Syrian Arab Republic', 'region' => 'Asia', 'currency_code' => 'SYP', 'currency_name' => 'Syrian pound'],
          ['code' => 'TWN', 'name' => 'Taiwan', 'region' => 'Asia', 'currency_code' => 'TWD', 'currency_name' => 'New Taiwan dollar'],
          ['code' => 'TJK', 'name' => 'Tajikistan', 'region' => 'Asia', 'currency_code' => 'TJS', 'currency_name' => 'Tajikistani somoni'],
          ['code' => 'TZA', 'name' => 'Tanzania, United Republic of', 'region' => 'Africa', 'currency_code' => 'TZS', 'currency_name' => 'Tanzanian shilling'],
          ['code' => 'THA', 'name' => 'Thailand', 'region' => 'Asia', 'currency_code' => 'THB', 'currency_name' => 'Thai baht'],
          ['code' => 'TLS', 'name' => 'Timor-Leste', 'region' => 'Asia', 'currency_code' => 'USD', 'currency_name' => 'United States dollar'],
          ['code' => 'TGO', 'name' => 'Togo', 'region' => 'Africa', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA franc'],
          ['code' => 'TKL', 'name' => 'Tokelau', 'region' => 'Oceania', 'currency_code' => 'NZD', 'currency_name' => 'New Zealand dollar'],
          ['code' => 'TON', 'name' => 'Tonga', 'region' => 'Oceania', 'currency_code' => 'TOP', 'currency_name' => 'Tongan paʻanga'],
          ['code' => 'TTO', 'name' => 'Trinidad and Tobago', 'region' => 'Americas', 'currency_code' => 'TTD', 'currency_name' => 'Trinidad and Tobago dollar'],
          ['code' => 'TUN', 'name' => 'Tunisia', 'region' => 'Africa', 'currency_code' => 'TND', 'currency_name' => 'Tunisian dinar'],
          ['code' => 'TUR', 'name' => 'Turkey', 'region' => 'Asia', 'currency_code' => 'TRY', 'currency_name' => 'Turkish lira'],
          ['code' => 'TKM', 'name' => 'Turkmenistan', 'region' => 'Asia', 'currency_code' => 'TMT', 'currency_name' => 'Turkmenistan manat'],
          ['code' => 'TCA', 'name' => 'Turks and Caicos Islands', 'region' => 'Americas', 'currency_code' => 'USD', 'currency_name' => 'United States dollar'],
          ['code' => 'TUV', 'name' => 'Tuvalu', 'region' => 'Oceania', 'currency_code' => 'AUD', 'currency_name' => 'Australian dollar'],
          ['code' => 'UGA', 'name' => 'Uganda', 'region' => 'Africa', 'currency_code' => 'UGX', 'currency_name' => 'Ugandan shilling'],
          ['code' => 'UKR', 'name' => 'Ukraine', 'region' => 'Europe', 'currency_code' => 'UAH', 'currency_name' => 'Ukrainian hryvnia'],
          ['code' => 'ARE', 'name' => 'United Arab Emirates', 'region' => 'Asia', 'currency_code' => 'AED', 'currency_name' => 'United Arab Emirates dirham'],
          ['code' => 'GBR', 'name' => 'United Kingdom of Great Britain and Northern Ireland', 'region' => 'Europe', 'currency_code' => 'GBP', 'currency_name' => 'British pound'],
          ['code' => 'USA', 'name' => 'United States of America', 'region' => 'Americas', 'currency_code' => 'USD', 'currency_name' => 'United States dollar'],
          ['code' => 'URY', 'name' => 'Uruguay', 'region' => 'Americas', 'currency_code' => 'UYU', 'currency_name' => 'Uruguayan peso'],
          ['code' => 'UZB', 'name' => 'Uzbekistan', 'region' => 'Asia', 'currency_code' => 'UZS', 'currency_name' => 'Uzbekistani so\'m'],
          ['code' => 'VUT', 'name' => 'Vanuatu', 'region' => 'Oceania', 'currency_code' => 'VUV', 'currency_name' => 'Vanuatu vatu'],
          ['code' => 'VEN', 'name' => 'Venezuela (Bolivarian Republic of)', 'region' => 'Americas', 'currency_code' => 'VEF', 'currency_name' => 'Venezuelan bolívar'],
          ['code' => 'VNM', 'name' => 'Viet Nam', 'region' => 'Asia', 'currency_code' => 'VND', 'currency_name' => 'Vietnamese đồng'],
          ['code' => 'WLF', 'name' => 'Wallis and Futuna', 'region' => 'Oceania', 'currency_code' => 'XPF', 'currency_name' => 'CFP franc'],
          ['code' => 'ESH', 'name' => 'Western Sahara', 'region' => 'Africa', 'currency_code' => 'MAD', 'currency_name' => 'Moroccan dirham'],
          ['code' => 'YEM', 'name' => 'Yemen', 'region' => 'Asia', 'currency_code' => 'YER', 'currency_name' => 'Yemeni rial'],
          ['code' => 'ZMB', 'name' => 'Zambia', 'region' => 'Africa', 'currency_code' => 'ZMW', 'currency_name' => 'Zambian kwacha'],
          ['code' => 'ZWE', 'name' => 'Zimbabwe', 'region' => 'Africa', 'currency_code' => 'BWP', 'currency_name' => 'Botswana pula']
      ];

      foreach ($countries as $country) {
          Country::create(array_merge($country, [
              'created_at' => Carbon::now(),
              'updated_at' => Carbon::now()
          ]));
      };
  }
}
