<?php

use App\Models\District;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class DistrictSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
      $districts = [
          ['state_id' => '1', 'name' => 'KABUPATEN SIMEULUE'],
          ['state_id' => '1', 'name' => 'KABUPATEN ACEH SINGKIL'],
          ['state_id' => '1', 'name' => 'KABUPATEN ACEH SELATAN'],
          ['state_id' => '1', 'name' => 'KABUPATEN ACEH TENGGARA'],
          ['state_id' => '1', 'name' => 'KABUPATEN ACEH TIMUR'],
          ['state_id' => '1', 'name' => 'KABUPATEN ACEH TENGAH'],
          ['state_id' => '1', 'name' => 'KABUPATEN ACEH BARAT'],
          ['state_id' => '1', 'name' => 'KABUPATEN ACEH BESAR'],
          ['state_id' => '1', 'name' => 'KABUPATEN PIDIE'],
          ['state_id' => '1', 'name' => 'KABUPATEN BIREUEN'],
          ['state_id' => '1', 'name' => 'KABUPATEN ACEH UTARA'],
          ['state_id' => '1', 'name' => 'KABUPATEN ACEH BARAT DAYA'],
          ['state_id' => '1', 'name' => 'KABUPATEN GAYO LUES'],
          ['state_id' => '1', 'name' => 'KABUPATEN ACEH TAMIANG'],
          ['state_id' => '1', 'name' => 'KABUPATEN NAGAN RAYA'],
          ['state_id' => '1', 'name' => 'KABUPATEN ACEH JAYA'],
          ['state_id' => '1', 'name' => 'KABUPATEN BENER MERIAH'],
          ['state_id' => '1', 'name' => 'KABUPATEN PIDIE JAYA'],
          ['state_id' => '1', 'name' => 'KOTA BANDA ACEH'],
          ['state_id' => '1', 'name' => 'KOTA SABANG'],
          ['state_id' => '1', 'name' => 'KOTA LANGSA'],
          ['state_id' => '1', 'name' => 'KOTA LHOKSEUMAWE'],
          ['state_id' => '1', 'name' => 'KOTA SUBULUSSALAM'],
          ['state_id' => '2', 'name' => 'KABUPATEN NIAS'],
          ['state_id' => '2', 'name' => 'KABUPATEN MANDAILING NATAL'],
          ['state_id' => '2', 'name' => 'KABUPATEN TAPANULI SELATAN'],
          ['state_id' => '2', 'name' => 'KABUPATEN TAPANULI TENGAH'],
          ['state_id' => '2', 'name' => 'KABUPATEN TAPANULI UTARA'],
          ['state_id' => '2', 'name' => 'KABUPATEN TOBA SAMOSIR'],
          ['state_id' => '2', 'name' => 'KABUPATEN LABUHAN BATU'],
          ['state_id' => '2', 'name' => 'KABUPATEN ASAHAN'],
          ['state_id' => '2', 'name' => 'KABUPATEN SIMALUNGUN'],
          ['state_id' => '2', 'name' => 'KABUPATEN DAIRI'],
          ['state_id' => '2', 'name' => 'KABUPATEN KARO'],
          ['state_id' => '2', 'name' => 'KABUPATEN DELI SERDANG'],
          ['state_id' => '2', 'name' => 'KABUPATEN LANGKAT'],
          ['state_id' => '2', 'name' => 'KABUPATEN NIAS SELATAN'],
          ['state_id' => '2', 'name' => 'KABUPATEN HUMBANG HASUNDUTAN'],
          ['state_id' => '2', 'name' => 'KABUPATEN PAKPAK BHARAT'],
          ['state_id' => '2', 'name' => 'KABUPATEN SAMOSIR'],
          ['state_id' => '2', 'name' => 'KABUPATEN SERDANG BEDAGAI'],
          ['state_id' => '2', 'name' => 'KABUPATEN BATU BARA'],
          ['state_id' => '2', 'name' => 'KABUPATEN PADANG LAWAS UTARA'],
          ['state_id' => '2', 'name' => 'KABUPATEN PADANG LAWAS'],
          ['state_id' => '2', 'name' => 'KABUPATEN LABUHAN BATU SELATAN'],
          ['state_id' => '2', 'name' => 'KABUPATEN LABUHAN BATU UTARA'],
          ['state_id' => '2', 'name' => 'KABUPATEN NIAS UTARA'],
          ['state_id' => '2', 'name' => 'KABUPATEN NIAS BARAT'],
          ['state_id' => '2', 'name' => 'KOTA SIBOLGA'],
          ['state_id' => '2', 'name' => 'KOTA TANJUNG BALAI'],
          ['state_id' => '2', 'name' => 'KOTA PEMATANG SIANTAR'],
          ['state_id' => '2', 'name' => 'KOTA TEBING TINGGI'],
          ['state_id' => '2', 'name' => 'KOTA MEDAN'],
          ['state_id' => '2', 'name' => 'KOTA BINJAI'],
          ['state_id' => '2', 'name' => 'KOTA PADANGSIDIMPUAN'],
          ['state_id' => '2', 'name' => 'KOTA GUNUNGSITOLI'],
          ['state_id' => '3', 'name' => 'KABUPATEN KEPULAUAN MENTAWAI'],
          ['state_id' => '3', 'name' => 'KABUPATEN PESISIR SELATAN'],
          ['state_id' => '3', 'name' => 'KABUPATEN SOLOK'],
          ['state_id' => '3', 'name' => 'KABUPATEN SIJUNJUNG'],
          ['state_id' => '3', 'name' => 'KABUPATEN TANAH DATAR'],
          ['state_id' => '3', 'name' => 'KABUPATEN PADANG PARIAMAN'],
          ['state_id' => '3', 'name' => 'KABUPATEN AGAM'],
          ['state_id' => '3', 'name' => 'KABUPATEN LIMA PULUH KOTA'],
          ['state_id' => '3', 'name' => 'KABUPATEN PASAMAN'],
          ['state_id' => '3', 'name' => 'KABUPATEN SOLOK SELATAN'],
          ['state_id' => '3', 'name' => 'KABUPATEN DHARMASRAYA'],
          ['state_id' => '3', 'name' => 'KABUPATEN PASAMAN BARAT'],
          ['state_id' => '3', 'name' => 'KOTA PADANG'],
          ['state_id' => '3', 'name' => 'KOTA SOLOK'],
          ['state_id' => '3', 'name' => 'KOTA SAWAH LUNTO'],
          ['state_id' => '3', 'name' => 'KOTA PADANG PANJANG'],
          ['state_id' => '3', 'name' => 'KOTA BUKITTINGGI'],
          ['state_id' => '3', 'name' => 'KOTA PAYAKUMBUH'],
          ['state_id' => '3', 'name' => 'KOTA PARIAMAN'],
          ['state_id' => '4', 'name' => 'KABUPATEN KUANTAN SINGINGI'],
          ['state_id' => '4', 'name' => 'KABUPATEN INDRAGIRI HULU'],
          ['state_id' => '4', 'name' => 'KABUPATEN INDRAGIRI HILIR'],
          ['state_id' => '4', 'name' => 'KABUPATEN PELALAWAN'],
          ['state_id' => '4', 'name' => 'KABUPATEN S I A K'],
          ['state_id' => '4', 'name' => 'KABUPATEN KAMPAR'],
          ['state_id' => '4', 'name' => 'KABUPATEN ROKAN HULU'],
          ['state_id' => '4', 'name' => 'KABUPATEN BENGKALIS'],
          ['state_id' => '4', 'name' => 'KABUPATEN ROKAN HILIR'],
          ['state_id' => '4', 'name' => 'KABUPATEN KEPULAUAN MERANTI'],
          ['state_id' => '4', 'name' => 'KOTA PEKANBARU'],
          ['state_id' => '4', 'name' => 'KOTA D U M A I'],
          ['state_id' => '5', 'name' => 'KABUPATEN KERINCI'],
          ['state_id' => '5', 'name' => 'KABUPATEN MERANGIN'],
          ['state_id' => '5', 'name' => 'KABUPATEN SAROLANGUN'],
          ['state_id' => '5', 'name' => 'KABUPATEN BATANG HARI'],
          ['state_id' => '5', 'name' => 'KABUPATEN MUARO JAMBI'],
          ['state_id' => '5', 'name' => 'KABUPATEN TANJUNG JABUNG TIMUR'],
          ['state_id' => '5', 'name' => 'KABUPATEN TANJUNG JABUNG BARAT'],
          ['state_id' => '5', 'name' => 'KABUPATEN TEBO'],
          ['state_id' => '5', 'name' => 'KABUPATEN BUNGO'],
          ['state_id' => '5', 'name' => 'KOTA JAMBI'],
          ['state_id' => '5', 'name' => 'KOTA SUNGAI PENUH'],
          ['state_id' => '6', 'name' => 'KABUPATEN OGAN KOMERING ULU'],
          ['state_id' => '6', 'name' => 'KABUPATEN OGAN KOMERING ILIR'],
          ['state_id' => '6', 'name' => 'KABUPATEN MUARA ENIM'],
          ['state_id' => '6', 'name' => 'KABUPATEN LAHAT'],
          ['state_id' => '6', 'name' => 'KABUPATEN MUSI RAWAS'],
          ['state_id' => '6', 'name' => 'KABUPATEN MUSI BANYUASIN'],
          ['state_id' => '6', 'name' => 'KABUPATEN BANYU ASIN'],
          ['state_id' => '6', 'name' => 'KABUPATEN OGAN KOMERING ULU SELATAN'],
          ['state_id' => '6', 'name' => 'KABUPATEN OGAN KOMERING ULU TIMUR'],
          ['state_id' => '6', 'name' => 'KABUPATEN OGAN ILIR'],
          ['state_id' => '6', 'name' => 'KABUPATEN EMPAT LAWANG'],
          ['state_id' => '6', 'name' => 'KABUPATEN PENUKAL ABAB LEMATANG ILIR'],
          ['state_id' => '6', 'name' => 'KABUPATEN MUSI RAWAS UTARA'],
          ['state_id' => '6', 'name' => 'KOTA PALEMBANG'],
          ['state_id' => '6', 'name' => 'KOTA PRABUMULIH'],
          ['state_id' => '6', 'name' => 'KOTA PAGAR ALAM'],
          ['state_id' => '6', 'name' => 'KOTA LUBUKLINGGAU'],
          ['state_id' => '7', 'name' => 'KABUPATEN BENGKULU SELATAN'],
          ['state_id' => '7', 'name' => 'KABUPATEN REJANG LEBONG'],
          ['state_id' => '7', 'name' => 'KABUPATEN BENGKULU UTARA'],
          ['state_id' => '7', 'name' => 'KABUPATEN KAUR'],
          ['state_id' => '7', 'name' => 'KABUPATEN SELUMA'],
          ['state_id' => '7', 'name' => 'KABUPATEN MUKOMUKO'],
          ['state_id' => '7', 'name' => 'KABUPATEN LEBONG'],
          ['state_id' => '7', 'name' => 'KABUPATEN KEPAHIANG'],
          ['state_id' => '7', 'name' => 'KABUPATEN BENGKULU TENGAH'],
          ['state_id' => '7', 'name' => 'KOTA BENGKULU'],
          ['state_id' => '8', 'name' => 'KABUPATEN LAMPUNG BARAT'],
          ['state_id' => '8', 'name' => 'KABUPATEN TANGGAMUS'],
          ['state_id' => '8', 'name' => 'KABUPATEN LAMPUNG SELATAN'],
          ['state_id' => '8', 'name' => 'KABUPATEN LAMPUNG TIMUR'],
          ['state_id' => '8', 'name' => 'KABUPATEN LAMPUNG TENGAH'],
          ['state_id' => '8', 'name' => 'KABUPATEN LAMPUNG UTARA'],
          ['state_id' => '8', 'name' => 'KABUPATEN WAY KANAN'],
          ['state_id' => '8', 'name' => 'KABUPATEN TULANGBAWANG'],
          ['state_id' => '8', 'name' => 'KABUPATEN PESAWARAN'],
          ['state_id' => '8', 'name' => 'KABUPATEN PRINGSEWU'],
          ['state_id' => '8', 'name' => 'KABUPATEN MESUJI'],
          ['state_id' => '8', 'name' => 'KABUPATEN TULANG BAWANG BARAT'],
          ['state_id' => '8', 'name' => 'KABUPATEN PESISIR BARAT'],
          ['state_id' => '8', 'name' => 'KOTA BANDAR LAMPUNG'],
          ['state_id' => '8', 'name' => 'KOTA METRO'],
          ['state_id' => '9', 'name' => 'KABUPATEN BANGKA'],
          ['state_id' => '9', 'name' => 'KABUPATEN BELITUNG'],
          ['state_id' => '9', 'name' => 'KABUPATEN BANGKA BARAT'],
          ['state_id' => '9', 'name' => 'KABUPATEN BANGKA TENGAH'],
          ['state_id' => '9', 'name' => 'KABUPATEN BANGKA SELATAN'],
          ['state_id' => '9', 'name' => 'KABUPATEN BELITUNG TIMUR'],
          ['state_id' => '9', 'name' => 'KOTA PANGKAL PINANG'],
          ['state_id' => '10', 'name' => 'KABUPATEN KARIMUN'],
          ['state_id' => '10', 'name' => 'KABUPATEN BINTAN'],
          ['state_id' => '10', 'name' => 'KABUPATEN NATUNA'],
          ['state_id' => '10', 'name' => 'KABUPATEN LINGGA'],
          ['state_id' => '10', 'name' => 'KABUPATEN KEPULAUAN ANAMBAS'],
          ['state_id' => '10', 'name' => 'KOTA B A T A M'],
          ['state_id' => '10', 'name' => 'KOTA TANJUNG PINANG'],
          ['state_id' => '11', 'name' => 'KABUPATEN KEPULAUAN SERIBU'],
          ['state_id' => '11', 'name' => 'KOTA JAKARTA SELATAN'],
          ['state_id' => '11', 'name' => 'KOTA JAKARTA TIMUR'],
          ['state_id' => '11', 'name' => 'KOTA JAKARTA PUSAT'],
          ['state_id' => '11', 'name' => 'KOTA JAKARTA BARAT'],
          ['state_id' => '11', 'name' => 'KOTA JAKARTA UTARA'],
          ['state_id' => '12', 'name' => 'KABUPATEN BOGOR'],
          ['state_id' => '12', 'name' => 'KABUPATEN SUKABUMI'],
          ['state_id' => '12', 'name' => 'KABUPATEN CIANJUR'],
          ['state_id' => '12', 'name' => 'KABUPATEN BANDUNG'],
          ['state_id' => '12', 'name' => 'KABUPATEN GARUT'],
          ['state_id' => '12', 'name' => 'KABUPATEN TASIKMALAYA'],
          ['state_id' => '12', 'name' => 'KABUPATEN CIAMIS'],
          ['state_id' => '12', 'name' => 'KABUPATEN KUNINGAN'],
          ['state_id' => '12', 'name' => 'KABUPATEN CIREBON'],
          ['state_id' => '12', 'name' => 'KABUPATEN MAJALENGKA'],
          ['state_id' => '12', 'name' => 'KABUPATEN SUMEDANG'],
          ['state_id' => '12', 'name' => 'KABUPATEN INDRAMAYU'],
          ['state_id' => '12', 'name' => 'KABUPATEN SUBANG'],
          ['state_id' => '12', 'name' => 'KABUPATEN PURWAKARTA'],
          ['state_id' => '12', 'name' => 'KABUPATEN KARAWANG'],
          ['state_id' => '12', 'name' => 'KABUPATEN BEKASI'],
          ['state_id' => '12', 'name' => 'KABUPATEN BANDUNG BARAT'],
          ['state_id' => '12', 'name' => 'KABUPATEN PANGANDARAN'],
          ['state_id' => '12', 'name' => 'KOTA BOGOR'],
          ['state_id' => '12', 'name' => 'KOTA SUKABUMI'],
          ['state_id' => '12', 'name' => 'KOTA BANDUNG'],
          ['state_id' => '12', 'name' => 'KOTA CIREBON'],
          ['state_id' => '12', 'name' => 'KOTA BEKASI'],
          ['state_id' => '12', 'name' => 'KOTA DEPOK'],
          ['state_id' => '12', 'name' => 'KOTA CIMAHI'],
          ['state_id' => '12', 'name' => 'KOTA TASIKMALAYA'],
          ['state_id' => '12', 'name' => 'KOTA BANJAR'],
          ['state_id' => '13', 'name' => 'KABUPATEN CILACAP'],
          ['state_id' => '13', 'name' => 'KABUPATEN BANYUMAS'],
          ['state_id' => '13', 'name' => 'KABUPATEN PURBALINGGA'],
          ['state_id' => '13', 'name' => 'KABUPATEN BANJARNEGARA'],
          ['state_id' => '13', 'name' => 'KABUPATEN KEBUMEN'],
          ['state_id' => '13', 'name' => 'KABUPATEN PURWOREJO'],
          ['state_id' => '13', 'name' => 'KABUPATEN WONOSOBO'],
          ['state_id' => '13', 'name' => 'KABUPATEN MAGELANG'],
          ['state_id' => '13', 'name' => 'KABUPATEN BOYOLALI'],
          ['state_id' => '13', 'name' => 'KABUPATEN KLATEN'],
          ['state_id' => '13', 'name' => 'KABUPATEN SUKOHARJO'],
          ['state_id' => '13', 'name' => 'KABUPATEN WONOGIRI'],
          ['state_id' => '13', 'name' => 'KABUPATEN KARANGANYAR'],
          ['state_id' => '13', 'name' => 'KABUPATEN SRAGEN'],
          ['state_id' => '13', 'name' => 'KABUPATEN GROBOGAN'],
          ['state_id' => '13', 'name' => 'KABUPATEN BLORA'],
          ['state_id' => '13', 'name' => 'KABUPATEN REMBANG'],
          ['state_id' => '13', 'name' => 'KABUPATEN PATI'],
          ['state_id' => '13', 'name' => 'KABUPATEN KUDUS'],
          ['state_id' => '13', 'name' => 'KABUPATEN JEPARA'],
          ['state_id' => '13', 'name' => 'KABUPATEN DEMAK'],
          ['state_id' => '13', 'name' => 'KABUPATEN SEMARANG'],
          ['state_id' => '13', 'name' => 'KABUPATEN TEMANGGUNG'],
          ['state_id' => '13', 'name' => 'KABUPATEN KENDAL'],
          ['state_id' => '13', 'name' => 'KABUPATEN BATANG'],
          ['state_id' => '13', 'name' => 'KABUPATEN PEKALONGAN'],
          ['state_id' => '13', 'name' => 'KABUPATEN PEMALANG'],
          ['state_id' => '13', 'name' => 'KABUPATEN TEGAL'],
          ['state_id' => '13', 'name' => 'KABUPATEN BREBES'],
          ['state_id' => '13', 'name' => 'KOTA MAGELANG'],
          ['state_id' => '13', 'name' => 'KOTA SURAKARTA'],
          ['state_id' => '13', 'name' => 'KOTA SALATIGA'],
          ['state_id' => '13', 'name' => 'KOTA SEMARANG'],
          ['state_id' => '13', 'name' => 'KOTA PEKALONGAN'],
          ['state_id' => '13', 'name' => 'KOTA TEGAL'],
          ['state_id' => '14', 'name' => 'KABUPATEN KULON PROGO'],
          ['state_id' => '14', 'name' => 'KABUPATEN BANTUL'],
          ['state_id' => '14', 'name' => 'KABUPATEN GUNUNG KIDUL'],
          ['state_id' => '14', 'name' => 'KABUPATEN SLEMAN'],
          ['state_id' => '14', 'name' => 'KOTA YOGYAKARTA'],
          ['state_id' => '15', 'name' => 'KABUPATEN PACITAN'],
          ['state_id' => '15', 'name' => 'KABUPATEN PONOROGO'],
          ['state_id' => '15', 'name' => 'KABUPATEN TRENGGALEK'],
          ['state_id' => '15', 'name' => 'KABUPATEN TULUNGAGUNG'],
          ['state_id' => '15', 'name' => 'KABUPATEN BLITAR'],
          ['state_id' => '15', 'name' => 'KABUPATEN KEDIRI'],
          ['state_id' => '15', 'name' => 'KABUPATEN MALANG'],
          ['state_id' => '15', 'name' => 'KABUPATEN LUMAJANG'],
          ['state_id' => '15', 'name' => 'KABUPATEN JEMBER'],
          ['state_id' => '15', 'name' => 'KABUPATEN BANYUWANGI'],
          ['state_id' => '15', 'name' => 'KABUPATEN BONDOWOSO'],
          ['state_id' => '15', 'name' => 'KABUPATEN SITUBONDO'],
          ['state_id' => '15', 'name' => 'KABUPATEN PROBOLINGGO'],
          ['state_id' => '15', 'name' => 'KABUPATEN PASURUAN'],
          ['state_id' => '15', 'name' => 'KABUPATEN SIDOARJO'],
          ['state_id' => '15', 'name' => 'KABUPATEN MOJOKERTO'],
          ['state_id' => '15', 'name' => 'KABUPATEN JOMBANG'],
          ['state_id' => '15', 'name' => 'KABUPATEN NGANJUK'],
          ['state_id' => '15', 'name' => 'KABUPATEN MADIUN'],
          ['state_id' => '15', 'name' => 'KABUPATEN MAGETAN'],
          ['state_id' => '15', 'name' => 'KABUPATEN NGAWI'],
          ['state_id' => '15', 'name' => 'KABUPATEN BOJONEGORO'],
          ['state_id' => '15', 'name' => 'KABUPATEN TUBAN'],
          ['state_id' => '15', 'name' => 'KABUPATEN LAMONGAN'],
          ['state_id' => '15', 'name' => 'KABUPATEN GRESIK'],
          ['state_id' => '15', 'name' => 'KABUPATEN BANGKALAN'],
          ['state_id' => '15', 'name' => 'KABUPATEN SAMPANG'],
          ['state_id' => '15', 'name' => 'KABUPATEN PAMEKASAN'],
          ['state_id' => '15', 'name' => 'KABUPATEN SUMENEP'],
          ['state_id' => '15', 'name' => 'KOTA KEDIRI'],
          ['state_id' => '15', 'name' => 'KOTA BLITAR'],
          ['state_id' => '15', 'name' => 'KOTA MALANG'],
          ['state_id' => '15', 'name' => 'KOTA PROBOLINGGO'],
          ['state_id' => '15', 'name' => 'KOTA PASURUAN'],
          ['state_id' => '15', 'name' => 'KOTA MOJOKERTO'],
          ['state_id' => '15', 'name' => 'KOTA MADIUN'],
          ['state_id' => '15', 'name' => 'KOTA SURABAYA'],
          ['state_id' => '15', 'name' => 'KOTA BATU'],
          ['state_id' => '16', 'name' => 'KABUPATEN PANDEGLANG'],
          ['state_id' => '16', 'name' => 'KABUPATEN LEBAK'],
          ['state_id' => '16', 'name' => 'KABUPATEN TANGERANG'],
          ['state_id' => '16', 'name' => 'KABUPATEN SERANG'],
          ['state_id' => '16', 'name' => 'KOTA TANGERANG'],
          ['state_id' => '16', 'name' => 'KOTA CILEGON'],
          ['state_id' => '16', 'name' => 'KOTA SERANG'],
          ['state_id' => '16', 'name' => 'KOTA TANGERANG SELATAN'],
          ['state_id' => '17', 'name' => 'KABUPATEN JEMBRANA'],
          ['state_id' => '17', 'name' => 'KABUPATEN TABANAN'],
          ['state_id' => '17', 'name' => 'KABUPATEN BADUNG'],
          ['state_id' => '17', 'name' => 'KABUPATEN GIANYAR'],
          ['state_id' => '17', 'name' => 'KABUPATEN KLUNGKUNG'],
          ['state_id' => '17', 'name' => 'KABUPATEN BANGLI'],
          ['state_id' => '17', 'name' => 'KABUPATEN KARANG ASEM'],
          ['state_id' => '17', 'name' => 'KABUPATEN BULELENG'],
          ['state_id' => '17', 'name' => 'KOTA DENPASAR'],
          ['state_id' => '18', 'name' => 'KABUPATEN LOMBOK BARAT'],
          ['state_id' => '18', 'name' => 'KABUPATEN LOMBOK TENGAH'],
          ['state_id' => '18', 'name' => 'KABUPATEN LOMBOK TIMUR'],
          ['state_id' => '18', 'name' => 'KABUPATEN SUMBAWA'],
          ['state_id' => '18', 'name' => 'KABUPATEN DOMPU'],
          ['state_id' => '18', 'name' => 'KABUPATEN BIMA'],
          ['state_id' => '18', 'name' => 'KABUPATEN SUMBAWA BARAT'],
          ['state_id' => '18', 'name' => 'KABUPATEN LOMBOK UTARA'],
          ['state_id' => '18', 'name' => 'KOTA MATARAM'],
          ['state_id' => '18', 'name' => 'KOTA BIMA'],
          ['state_id' => '19', 'name' => 'KABUPATEN SUMBA BARAT'],
          ['state_id' => '19', 'name' => 'KABUPATEN SUMBA TIMUR'],
          ['state_id' => '19', 'name' => 'KABUPATEN KUPANG'],
          ['state_id' => '19', 'name' => 'KABUPATEN TIMOR TENGAH SELATAN'],
          ['state_id' => '19', 'name' => 'KABUPATEN TIMOR TENGAH UTARA'],
          ['state_id' => '19', 'name' => 'KABUPATEN BELU'],
          ['state_id' => '19', 'name' => 'KABUPATEN ALOR'],
          ['state_id' => '19', 'name' => 'KABUPATEN LEMBATA'],
          ['state_id' => '19', 'name' => 'KABUPATEN FLORES TIMUR'],
          ['state_id' => '19', 'name' => 'KABUPATEN SIKKA'],
          ['state_id' => '19', 'name' => 'KABUPATEN ENDE'],
          ['state_id' => '19', 'name' => 'KABUPATEN NGADA'],
          ['state_id' => '19', 'name' => 'KABUPATEN MANGGARAI'],
          ['state_id' => '19', 'name' => 'KABUPATEN ROTE NDAO'],
          ['state_id' => '19', 'name' => 'KABUPATEN MANGGARAI BARAT'],
          ['state_id' => '19', 'name' => 'KABUPATEN SUMBA TENGAH'],
          ['state_id' => '19', 'name' => 'KABUPATEN SUMBA BARAT DAYA'],
          ['state_id' => '19', 'name' => 'KABUPATEN NAGEKEO'],
          ['state_id' => '19', 'name' => 'KABUPATEN MANGGARAI TIMUR'],
          ['state_id' => '19', 'name' => 'KABUPATEN SABU RAIJUA'],
          ['state_id' => '19', 'name' => 'KABUPATEN MALAKA'],
          ['state_id' => '19', 'name' => 'KOTA KUPANG'],
          ['state_id' => '20', 'name' => 'KABUPATEN SAMBAS'],
          ['state_id' => '20', 'name' => 'KABUPATEN BENGKAYANG'],
          ['state_id' => '20', 'name' => 'KABUPATEN LANDAK'],
          ['state_id' => '20', 'name' => 'KABUPATEN MEMPAWAH'],
          ['state_id' => '20', 'name' => 'KABUPATEN SANGGAU'],
          ['state_id' => '20', 'name' => 'KABUPATEN KETAPANG'],
          ['state_id' => '20', 'name' => 'KABUPATEN SINTANG'],
          ['state_id' => '20', 'name' => 'KABUPATEN KAPUAS HULU'],
          ['state_id' => '20', 'name' => 'KABUPATEN SEKADAU'],
          ['state_id' => '20', 'name' => 'KABUPATEN MELAWI'],
          ['state_id' => '20', 'name' => 'KABUPATEN KAYONG UTARA'],
          ['state_id' => '20', 'name' => 'KABUPATEN KUBU RAYA'],
          ['state_id' => '20', 'name' => 'KOTA PONTIANAK'],
          ['state_id' => '20', 'name' => 'KOTA SINGKAWANG'],
          ['state_id' => '21', 'name' => 'KABUPATEN KOTAWARINGIN BARAT'],
          ['state_id' => '21', 'name' => 'KABUPATEN KOTAWARINGIN TIMUR'],
          ['state_id' => '21', 'name' => 'KABUPATEN KAPUAS'],
          ['state_id' => '21', 'name' => 'KABUPATEN BARITO SELATAN'],
          ['state_id' => '21', 'name' => 'KABUPATEN BARITO UTARA'],
          ['state_id' => '21', 'name' => 'KABUPATEN SUKAMARA'],
          ['state_id' => '21', 'name' => 'KABUPATEN LAMANDAU'],
          ['state_id' => '21', 'name' => 'KABUPATEN SERUYAN'],
          ['state_id' => '21', 'name' => 'KABUPATEN KATINGAN'],
          ['state_id' => '21', 'name' => 'KABUPATEN PULANG PISAU'],
          ['state_id' => '21', 'name' => 'KABUPATEN GUNUNG MAS'],
          ['state_id' => '21', 'name' => 'KABUPATEN BARITO TIMUR'],
          ['state_id' => '21', 'name' => 'KABUPATEN MURUNG RAYA'],
          ['state_id' => '21', 'name' => 'KOTA PALANGKA RAYA'],
          ['state_id' => '22', 'name' => 'KABUPATEN TANAH LAUT'],
          ['state_id' => '22', 'name' => 'KABUPATEN KOTA BARU'],
          ['state_id' => '22', 'name' => 'KABUPATEN BANJAR'],
          ['state_id' => '22', 'name' => 'KABUPATEN BARITO KUALA'],
          ['state_id' => '22', 'name' => 'KABUPATEN TAPIN'],
          ['state_id' => '22', 'name' => 'KABUPATEN HULU SUNGAI SELATAN'],
          ['state_id' => '22', 'name' => 'KABUPATEN HULU SUNGAI TENGAH'],
          ['state_id' => '22', 'name' => 'KABUPATEN HULU SUNGAI UTARA'],
          ['state_id' => '22', 'name' => 'KABUPATEN TABALONG'],
          ['state_id' => '22', 'name' => 'KABUPATEN TANAH BUMBU'],
          ['state_id' => '22', 'name' => 'KABUPATEN BALANGAN'],
          ['state_id' => '22', 'name' => 'KOTA BANJARMASIN'],
          ['state_id' => '22', 'name' => 'KOTA BANJAR BARU'],
          ['state_id' => '23', 'name' => 'KABUPATEN PASER'],
          ['state_id' => '23', 'name' => 'KABUPATEN KUTAI BARAT'],
          ['state_id' => '23', 'name' => 'KABUPATEN KUTAI KARTANEGARA'],
          ['state_id' => '23', 'name' => 'KABUPATEN KUTAI TIMUR'],
          ['state_id' => '23', 'name' => 'KABUPATEN BERAU'],
          ['state_id' => '23', 'name' => 'KABUPATEN PENAJAM PASER UTARA'],
          ['state_id' => '23', 'name' => 'KABUPATEN MAHAKAM HULU'],
          ['state_id' => '23', 'name' => 'KOTA BALIKPAPAN'],
          ['state_id' => '23', 'name' => 'KOTA SAMARINDA'],
          ['state_id' => '23', 'name' => 'KOTA BONTANG'],
          ['state_id' => '24', 'name' => 'KABUPATEN MALINAU'],
          ['state_id' => '24', 'name' => 'KABUPATEN BULUNGAN'],
          ['state_id' => '24', 'name' => 'KABUPATEN TANA TIDUNG'],
          ['state_id' => '24', 'name' => 'KABUPATEN NUNUKAN'],
          ['state_id' => '24', 'name' => 'KOTA TARAKAN'],
          ['state_id' => '25', 'name' => 'KABUPATEN BOLAANG MONGONDOW'],
          ['state_id' => '25', 'name' => 'KABUPATEN MINAHASA'],
          ['state_id' => '25', 'name' => 'KABUPATEN KEPULAUAN SANGIHE'],
          ['state_id' => '25', 'name' => 'KABUPATEN KEPULAUAN TALAUD'],
          ['state_id' => '25', 'name' => 'KABUPATEN MINAHASA SELATAN'],
          ['state_id' => '25', 'name' => 'KABUPATEN MINAHASA UTARA'],
          ['state_id' => '25', 'name' => 'KABUPATEN BOLAANG MONGONDOW UTARA'],
          ['state_id' => '25', 'name' => 'KABUPATEN SIAU TAGULANDANG BIARO'],
          ['state_id' => '25', 'name' => 'KABUPATEN MINAHASA TENGGARA'],
          ['state_id' => '25', 'name' => 'KABUPATEN BOLAANG MONGONDOW SELATAN'],
          ['state_id' => '25', 'name' => 'KABUPATEN BOLAANG MONGONDOW TIMUR'],
          ['state_id' => '25', 'name' => 'KOTA MANADO'],
          ['state_id' => '25', 'name' => 'KOTA BITUNG'],
          ['state_id' => '25', 'name' => 'KOTA TOMOHON'],
          ['state_id' => '25', 'name' => 'KOTA KOTAMOBAGU'],
          ['state_id' => '26', 'name' => 'KABUPATEN BANGGAI KEPULAUAN'],
          ['state_id' => '26', 'name' => 'KABUPATEN BANGGAI'],
          ['state_id' => '26', 'name' => 'KABUPATEN MOROWALI'],
          ['state_id' => '26', 'name' => 'KABUPATEN POSO'],
          ['state_id' => '26', 'name' => 'KABUPATEN DONGGALA'],
          ['state_id' => '26', 'name' => 'KABUPATEN TOLI-TOLI'],
          ['state_id' => '26', 'name' => 'KABUPATEN BUOL'],
          ['state_id' => '26', 'name' => 'KABUPATEN PARIGI MOUTONG'],
          ['state_id' => '26', 'name' => 'KABUPATEN TOJO UNA-UNA'],
          ['state_id' => '26', 'name' => 'KABUPATEN SIGI'],
          ['state_id' => '26', 'name' => 'KABUPATEN BANGGAI LAUT'],
          ['state_id' => '26', 'name' => 'KABUPATEN MOROWALI UTARA'],
          ['state_id' => '26', 'name' => 'KOTA PALU'],
          ['state_id' => '27', 'name' => 'KABUPATEN KEPULAUAN SELAYAR'],
          ['state_id' => '27', 'name' => 'KABUPATEN BULUKUMBA'],
          ['state_id' => '27', 'name' => 'KABUPATEN BANTAENG'],
          ['state_id' => '27', 'name' => 'KABUPATEN JENEPONTO'],
          ['state_id' => '27', 'name' => 'KABUPATEN TAKALAR'],
          ['state_id' => '27', 'name' => 'KABUPATEN GOWA'],
          ['state_id' => '27', 'name' => 'KABUPATEN SINJAI'],
          ['state_id' => '27', 'name' => 'KABUPATEN MAROS'],
          ['state_id' => '27', 'name' => 'KABUPATEN PANGKAJENE DAN KEPULAUAN'],
          ['state_id' => '27', 'name' => 'KABUPATEN BARRU'],
          ['state_id' => '27', 'name' => 'KABUPATEN BONE'],
          ['state_id' => '27', 'name' => 'KABUPATEN SOPPENG'],
          ['state_id' => '27', 'name' => 'KABUPATEN WAJO'],
          ['state_id' => '27', 'name' => 'KABUPATEN SIDENRENG RAPPANG'],
          ['state_id' => '27', 'name' => 'KABUPATEN PINRANG'],
          ['state_id' => '27', 'name' => 'KABUPATEN ENREKANG'],
          ['state_id' => '27', 'name' => 'KABUPATEN LUWU'],
          ['state_id' => '27', 'name' => 'KABUPATEN TANA TORAJA'],
          ['state_id' => '27', 'name' => 'KABUPATEN LUWU UTARA'],
          ['state_id' => '27', 'name' => 'KABUPATEN LUWU TIMUR'],
          ['state_id' => '27', 'name' => 'KABUPATEN TORAJA UTARA'],
          ['state_id' => '27', 'name' => 'KOTA MAKASSAR'],
          ['state_id' => '27', 'name' => 'KOTA PAREPARE'],
          ['state_id' => '27', 'name' => 'KOTA PALOPO'],
          ['state_id' => '28', 'name' => 'KABUPATEN BUTON'],
          ['state_id' => '28', 'name' => 'KABUPATEN MUNA'],
          ['state_id' => '28', 'name' => 'KABUPATEN KONAWE'],
          ['state_id' => '28', 'name' => 'KABUPATEN KOLAKA'],
          ['state_id' => '28', 'name' => 'KABUPATEN KONAWE SELATAN'],
          ['state_id' => '28', 'name' => 'KABUPATEN BOMBANA'],
          ['state_id' => '28', 'name' => 'KABUPATEN WAKATOBI'],
          ['state_id' => '28', 'name' => 'KABUPATEN KOLAKA UTARA'],
          ['state_id' => '28', 'name' => 'KABUPATEN BUTON UTARA'],
          ['state_id' => '28', 'name' => 'KABUPATEN KONAWE UTARA'],
          ['state_id' => '28', 'name' => 'KABUPATEN KOLAKA TIMUR'],
          ['state_id' => '28', 'name' => 'KABUPATEN KONAWE KEPULAUAN'],
          ['state_id' => '28', 'name' => 'KABUPATEN MUNA BARAT'],
          ['state_id' => '28', 'name' => 'KABUPATEN BUTON TENGAH'],
          ['state_id' => '28', 'name' => 'KABUPATEN BUTON SELATAN'],
          ['state_id' => '28', 'name' => 'KOTA KENDARI'],
          ['state_id' => '28', 'name' => 'KOTA BAUBAU'],
          ['state_id' => '29', 'name' => 'KABUPATEN BOALEMO'],
          ['state_id' => '29', 'name' => 'KABUPATEN GORONTALO'],
          ['state_id' => '29', 'name' => 'KABUPATEN POHUWATO'],
          ['state_id' => '29', 'name' => 'KABUPATEN BONE BOLANGO'],
          ['state_id' => '29', 'name' => 'KABUPATEN GORONTALO UTARA'],
          ['state_id' => '29', 'name' => 'KOTA GORONTALO'],
          ['state_id' => '30', 'name' => 'KABUPATEN MAJENE'],
          ['state_id' => '30', 'name' => 'KABUPATEN POLEWALI MANDAR'],
          ['state_id' => '30', 'name' => 'KABUPATEN MAMASA'],
          ['state_id' => '30', 'name' => 'KABUPATEN MAMUJU'],
          ['state_id' => '30', 'name' => 'KABUPATEN MAMUJU UTARA'],
          ['state_id' => '30', 'name' => 'KABUPATEN MAMUJU TENGAH'],
          ['state_id' => '31', 'name' => 'KABUPATEN MALUKU TENGGARA BARAT'],
          ['state_id' => '31', 'name' => 'KABUPATEN MALUKU TENGGARA'],
          ['state_id' => '31', 'name' => 'KABUPATEN MALUKU TENGAH'],
          ['state_id' => '31', 'name' => 'KABUPATEN BURU'],
          ['state_id' => '31', 'name' => 'KABUPATEN KEPULAUAN ARU'],
          ['state_id' => '31', 'name' => 'KABUPATEN SERAM BAGIAN BARAT'],
          ['state_id' => '31', 'name' => 'KABUPATEN SERAM BAGIAN TIMUR'],
          ['state_id' => '31', 'name' => 'KABUPATEN MALUKU BARAT DAYA'],
          ['state_id' => '31', 'name' => 'KABUPATEN BURU SELATAN'],
          ['state_id' => '31', 'name' => 'KOTA AMBON'],
          ['state_id' => '31', 'name' => 'KOTA TUAL'],
          ['state_id' => '32', 'name' => 'KABUPATEN HALMAHERA BARAT'],
          ['state_id' => '32', 'name' => 'KABUPATEN HALMAHERA TENGAH'],
          ['state_id' => '32', 'name' => 'KABUPATEN KEPULAUAN SULA'],
          ['state_id' => '32', 'name' => 'KABUPATEN HALMAHERA SELATAN'],
          ['state_id' => '32', 'name' => 'KABUPATEN HALMAHERA UTARA'],
          ['state_id' => '32', 'name' => 'KABUPATEN HALMAHERA TIMUR'],
          ['state_id' => '32', 'name' => 'KABUPATEN PULAU MOROTAI'],
          ['state_id' => '32', 'name' => 'KABUPATEN PULAU TALIABU'],
          ['state_id' => '32', 'name' => 'KOTA TERNATE'],
          ['state_id' => '32', 'name' => 'KOTA TIDORE KEPULAUAN'],
          ['state_id' => '33', 'name' => 'KABUPATEN FAKFAK'],
          ['state_id' => '33', 'name' => 'KABUPATEN KAIMANA'],
          ['state_id' => '33', 'name' => 'KABUPATEN TELUK WONDAMA'],
          ['state_id' => '33', 'name' => 'KABUPATEN TELUK BINTUNI'],
          ['state_id' => '33', 'name' => 'KABUPATEN MANOKWARI'],
          ['state_id' => '33', 'name' => 'KABUPATEN SORONG SELATAN'],
          ['state_id' => '33', 'name' => 'KABUPATEN SORONG'],
          ['state_id' => '33', 'name' => 'KABUPATEN RAJA AMPAT'],
          ['state_id' => '33', 'name' => 'KABUPATEN TAMBRAUW'],
          ['state_id' => '33', 'name' => 'KABUPATEN MAYBRAT'],
          ['state_id' => '33', 'name' => 'KABUPATEN MANOKWARI SELATAN'],
          ['state_id' => '33', 'name' => 'KABUPATEN PEGUNUNGAN ARFAK'],
          ['state_id' => '33', 'name' => 'KOTA SORONG'],
          ['state_id' => '34', 'name' => 'KABUPATEN MERAUKE'],
          ['state_id' => '34', 'name' => 'KABUPATEN JAYAWIJAYA'],
          ['state_id' => '34', 'name' => 'KABUPATEN JAYAPURA'],
          ['state_id' => '34', 'name' => 'KABUPATEN NABIRE'],
          ['state_id' => '34', 'name' => 'KABUPATEN KEPULAUAN YAPEN'],
          ['state_id' => '34', 'name' => 'KABUPATEN BIAK NUMFOR'],
          ['state_id' => '34', 'name' => 'KABUPATEN PANIAI'],
          ['state_id' => '34', 'name' => 'KABUPATEN PUNCAK JAYA'],
          ['state_id' => '34', 'name' => 'KABUPATEN MIMIKA'],
          ['state_id' => '34', 'name' => 'KABUPATEN BOVEN DIGOEL'],
          ['state_id' => '34', 'name' => 'KABUPATEN MAPPI'],
          ['state_id' => '34', 'name' => 'KABUPATEN ASMAT'],
          ['state_id' => '34', 'name' => 'KABUPATEN YAHUKIMO'],
          ['state_id' => '34', 'name' => 'KABUPATEN PEGUNUNGAN BINTANG'],
          ['state_id' => '34', 'name' => 'KABUPATEN TOLIKARA'],
          ['state_id' => '34', 'name' => 'KABUPATEN SARMI'],
          ['state_id' => '34', 'name' => 'KABUPATEN KEEROM'],
          ['state_id' => '34', 'name' => 'KABUPATEN WAROPEN'],
          ['state_id' => '34', 'name' => 'KABUPATEN SUPIORI'],
          ['state_id' => '34', 'name' => 'KABUPATEN MAMBERAMO RAYA'],
          ['state_id' => '34', 'name' => 'KABUPATEN NDUGA'],
          ['state_id' => '34', 'name' => 'KABUPATEN LANNY JAYA'],
          ['state_id' => '34', 'name' => 'KABUPATEN MAMBERAMO TENGAH'],
          ['state_id' => '34', 'name' => 'KABUPATEN YALIMO'],
          ['state_id' => '34', 'name' => 'KABUPATEN PUNCAK'],
          ['state_id' => '34', 'name' => 'KABUPATEN DOGIYAI'],
          ['state_id' => '34', 'name' => 'KABUPATEN INTAN JAYA'],
          ['state_id' => '34', 'name' => 'KABUPATEN DEIYAI'],
          ['state_id' => '34', 'name' => 'KOTA JAYAPURA'],
      ];

      foreach ($districts as $district) {
          District::create(array_merge($district, [
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ]));
      }
  }
}
